#include <stdlib.h>
#include <iostream>
#include "thread.h"
#include <assert.h>
#include <vector>
#include <string.h>
#include <fstream>
using namespace std;

void xyz1(void* args);
void xyz2(void* args);
void xyz3(void* args);
void xyz4(void* args);
void xyz5(void* args);
void xyz6(void* args);
void xyz7(void* args) ;
void xyz8(void* args);
void xyz9(void* args);
void xyz10(void* args);
void maker(void *args);
void xyz1(void* args) {
  thread_broadcast(0, 0);
  thread_broadcast(1, 0);
  thread_unlock(1);
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_broadcast(1, 0);
  thread_unlock(0);
  cout << "38690645" << endl;
  cout << "51126607" << endl;
  thread_broadcast(0, 0);
  cout << "108460354" << endl;
  thread_yield();
  thread_yield();
  thread_unlock(0);
  thread_lock(1);
  cout << "98556926" << endl;
  thread_lock(1);
  thread_broadcast(1, 1);
  thread_unlock(1);
  cout << "88533918" << endl;
  thread_lock(1);
  cout << "82898122" << endl;
  thread_wait(0, 0);
  thread_wait(0, 0);
  cout << "48274759" << endl;
  thread_broadcast(1, 0);
  thread_lock(0);
  thread_broadcast(0, 0);
  thread_signal(0, 1);
  thread_lock(1);
  thread_broadcast(1, 0);
  thread_broadcast(0, 1);
  thread_yield();
  thread_signal(1, 0);
  thread_broadcast(0, 1);
  thread_wait(0, 0);
  thread_broadcast(1, 1);
  thread_broadcast(0, 0);
  cout << "59684163" << endl;
  thread_signal(0, 0);
  thread_unlock(0);
  thread_wait(1, 0);
  thread_signal(0, 1);
  thread_yield();
  thread_wait(0, 0);
  thread_unlock(0);
  thread_unlock(0);
  thread_signal(1, 0);
  thread_broadcast(1, 0);
  thread_wait(1, 1);
  thread_lock(1);
  thread_signal(1, 1);
  thread_lock(0);
  thread_signal(1, 1);
  thread_broadcast(0, 1);
  thread_unlock(1);
  thread_unlock(0);
  thread_lock(0);
  thread_broadcast(1, 1);
  thread_wait(0, 0);
  thread_wait(1, 0);
  thread_wait(0, 1);
  thread_broadcast(0, 0);
  thread_wait(1, 1);
  thread_unlock(1);
  thread_wait(0, 0);
  cout << "86920711" << endl;
  thread_lock(0);
  thread_lock(1);
  cout << "91922858" << endl;
  thread_wait(1, 1);
  thread_lock(0);
  thread_broadcast(1, 1);
  thread_wait(0, 1);
  thread_wait(1, 1);
  thread_broadcast(1, 1);
  thread_unlock(0);
  thread_signal(0, 0);
  thread_lock(1);
  thread_lock(1);
  thread_signal(0, 1);
  thread_unlock(0);
  thread_yield();
  thread_wait(1, 0);
  thread_unlock(0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_signal(1, 1);
  thread_signal(1, 0);
  thread_unlock(0);
  thread_signal(1, 0);
  thread_unlock(1);
  thread_lock(1);
  thread_lock(1);
  thread_unlock(0);
  thread_yield();
  thread_unlock(1);
  cout << "118032848" << endl;
  thread_wait(0, 1);
  thread_unlock(0);
  thread_lock(0);
  cout << "62687188" << endl;
  cout << "287332" << endl;
  cout << "62139909" << endl;
  cout << "12680513" << endl;
  thread_broadcast(1, 0);
  thread_lock(1);
  cout << "87412908" << endl;
  thread_signal(0, 1);
  thread_lock(1);
  thread_lock(0);
  thread_lock(0);
  thread_broadcast(0, 1);
  thread_wait(0, 0);
  thread_yield();
  thread_lock(1);
  thread_lock(0);
  thread_unlock(0);
  thread_broadcast(1, 1);
  cout << "94018532" << endl;
  thread_signal(0, 1);
  thread_signal(0, 1);
  thread_lock(1);
  thread_unlock(1);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_broadcast(1, 1);
  thread_wait(1, 0);
  thread_signal(1, 1);
  thread_lock(0);
  thread_lock(1);
  thread_lock(1);
  thread_signal(0, 0);
  thread_wait(1, 0);
  thread_wait(1, 1);
  thread_broadcast(0, 1);
  cout << "54245154" << endl;
  thread_signal(0, 1);
  thread_yield();
  thread_lock(0);
  thread_unlock(1);
  thread_signal(1, 1);
  thread_signal(0, 0);
  thread_unlock(0);
  thread_signal(1, 0);
  thread_signal(0, 0);
  thread_lock(0);
  thread_broadcast(0, 1);
  thread_wait(0, 0);
  thread_lock(1);
  thread_lock(0);
  thread_broadcast(1, 0);
}

void xyz2(void* args) {
  thread_broadcast(9, 4);
  thread_wait(6, 4);
  thread_yield();
  thread_signal(10, 11);
  thread_unlock(6);
  thread_yield();
  thread_lock(11);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(11, 11);
  thread_signal(1, 11);
  thread_lock(3);
  thread_broadcast(8, 12);
  cout << "103340300" << endl;
  thread_yield();
  thread_signal(11, 9);
  thread_wait(10, 1);
  thread_unlock(11);
  thread_yield();
  thread_lock(5);
  thread_broadcast(10, 0);
  thread_signal(9, 4);
  thread_lock(9);
  thread_signal(6, 4);
  thread_signal(10, 7);
  thread_unlock(2);
  thread_yield();
  thread_signal(1, 4);
  thread_wait(0, 2);
  cout << "35797541" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(12);
  thread_yield();
  thread_yield();
  thread_broadcast(11, 0);
  thread_signal(1, 3);
  thread_unlock(1);
  thread_yield();
  thread_lock(1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_unlock(8);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(6, 6);
  thread_yield();
  thread_yield();
  thread_broadcast(5, 4);
  thread_yield();
  thread_lock(11);
  thread_lock(2);
  cout << "73646753" << endl;
  thread_yield();
  thread_yield();
  thread_unlock(11);
  thread_yield();
  thread_lock(11);
  thread_yield();
  thread_yield();
  cout << "56318656" << endl;
  thread_wait(10, 0);
}

void xyz3(void* args) {
  thread_lock(0);
  thread_broadcast(2, 2);
  thread_yield();
  thread_lock(1);
  thread_lock(5);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  cout << "12380170" << endl;
  thread_unlock(0);
  thread_signal(5, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_broadcast(5, 3);
  thread_wait(0, 5);
  thread_broadcast(4, 2);
  thread_yield();
  thread_yield();
  cout << "5836741" << endl;
  thread_signal(2, 1);
  thread_wait(5, 6);
  thread_lock(4);
  thread_broadcast(3, 0);
  thread_lock(4);
  cout << "10245069" << endl;
}

void xyz4(void* args) {
  cout << "104255508" << endl;
  cout << "51789768" << endl;
  thread_wait(6, 6);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(6, 3);
  thread_broadcast(6, 0);
  thread_yield();
  thread_unlock(1);
  thread_broadcast(5, 4);
  thread_yield();
  thread_broadcast(4, 5);
  thread_unlock(4);
  thread_wait(6, 0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  cout << "82052954" << endl;
  cout << "31056251" << endl;
  thread_broadcast(2, 8);
  thread_unlock(0);
  thread_wait(8, 7);
  thread_yield();
  thread_signal(3, 8);
  thread_yield();
  thread_broadcast(2, 7);
  thread_yield();
  cout << "108717238" << endl;
  thread_unlock(2);
  thread_yield();
  thread_yield();
  thread_broadcast(1, 0);
  thread_lock(0);
  thread_yield();
  thread_wait(4, 2);
  thread_signal(4, 8);
  thread_lock(6);
  thread_signal(4, 0);
  thread_yield();
  thread_yield();
  cout << "115877566" << endl;
  cout << "44034661" << endl;
  thread_yield();
  cout << "114884485" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_signal(0, 5);
  thread_wait(1, 7);
}

void xyz5(void* args) {
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(3);
  thread_lock(11);
  thread_signal(6, 8);
  thread_broadcast(0, 5);
  thread_unlock(11);
  thread_lock(15);
  thread_yield();
  thread_lock(0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_broadcast(4, 0);
  thread_signal(5, 3);
  thread_yield();
  thread_broadcast(14, 14);
  thread_wait(14, 8);
  thread_signal(18, 14);
  thread_signal(2, 5);
  thread_yield();
  thread_signal(17, 11);
  thread_yield();
  thread_yield();
  thread_broadcast(12, 6);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(16, 13);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(17, 10);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(3, 1);
  thread_yield();
  thread_broadcast(4, 11);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(12, 2);
  thread_yield();
  thread_lock(11);
  thread_lock(10);
  thread_yield();
  thread_lock(16);
  cout << "88922" << endl;
  thread_wait(9, 14);
  thread_broadcast(12, 0);
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_broadcast(1, 1);
  cout << "936940" << endl;
  thread_unlock(1);
  thread_broadcast(11, 3);
  thread_signal(12, 7);
  thread_broadcast(2, 2);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(9, 6);
  thread_unlock(1);
  thread_signal(15, 10);
  thread_broadcast(4, 3);
  thread_broadcast(14, 0);
  thread_wait(11, 18);
  thread_signal(5, 8);
  thread_unlock(7);
  thread_yield();
  thread_yield();
  thread_signal(3, 14);
  thread_wait(13, 12);
  thread_lock(8);
  thread_yield();
  thread_yield();
  thread_unlock(8);
  thread_yield();
  thread_broadcast(5, 6);
  thread_signal(0, 9);
  thread_yield();
  thread_lock(17);
  thread_yield();
  thread_yield();
  thread_wait(15, 18);
  thread_broadcast(7, 7);
  thread_yield();
  thread_yield();
  thread_lock(18);
  thread_yield();
  thread_broadcast(8, 14);
  thread_broadcast(15, 2);
  thread_signal(9, 17);
  thread_wait(7, 11);
  thread_unlock(0);
  thread_yield();
  thread_lock(12);
  thread_broadcast(18, 8);
  cout << "467775" << endl;
  thread_broadcast(4, 13);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(5, 17);
  thread_signal(15, 18);
  cout << "804215" << endl;
  thread_yield();
  thread_yield();
  thread_broadcast(5, 0);
  cout << "364542" << endl;
  thread_unlock(6);
  thread_lock(4);
  thread_signal(15, 8);
  thread_signal(11, 8);
  thread_unlock(1);
  thread_wait(0, 5);
}

void xyz6(void* args) {
  thread_yield();
  thread_yield();
  thread_lock(3);
  thread_unlock(2);
  thread_unlock(3);
  thread_yield();
  cout << "470413" << endl;
  thread_wait(1, 2);
  thread_wait(1, 3);
  thread_yield();
  thread_wait(1, 1);
  thread_unlock(2);
  cout << "1034802" << endl;
  thread_yield();
  thread_signal(1, 0);
  thread_broadcast(3, 3);
  thread_broadcast(2, 3);
  thread_unlock(2);
  thread_yield();
  thread_broadcast(1, 2);
  thread_yield();
  cout << "1194320" << endl;
  thread_signal(1, 2);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_broadcast(2, 3);
  thread_yield();
  thread_lock(2);
  thread_signal(1, 2);
  thread_signal(3, 1);
  thread_yield();
  cout << "1195971" << endl;
  cout << "974710" << endl;
  thread_unlock(3);
  thread_yield();
  thread_wait(2, 2);
  thread_yield();
  thread_lock(3);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_unlock(2);
  thread_unlock(0);
}

void xyz7(void* args) {
  thread_yield();
  thread_wait(3, 11);
  thread_unlock(7);
  thread_broadcast(3, 9);
  thread_yield();
  thread_broadcast(8, 2);
  thread_unlock(7);
  thread_wait(10, 4);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(12, 10);
  thread_lock(9);
  thread_signal(10, 1);
  thread_yield();
  thread_lock(2);
  thread_yield();
  thread_yield();
  cout << "621878" << endl;
  thread_lock(7);
  thread_yield();
  thread_unlock(7);
  cout << "2335115" << endl;
  thread_wait(12, 6);
  cout << "10464" << endl;
  thread_yield();
  thread_broadcast(12, 7);
  thread_yield();
  thread_signal(4, 8);
  thread_signal(5, 0);
  thread_signal(12, 4);
  thread_signal(12, 13);
  thread_yield();
  thread_lock(7);
  thread_signal(12, 12);
  thread_yield();
  thread_yield();
  thread_signal(7, 3);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(13, 11);
  thread_yield();
  cout << "2009549" << endl;
  thread_broadcast(0, 5);
  thread_broadcast(5, 8);
  thread_yield();
  thread_unlock(0);
  thread_yield();
  cout << "596666" << endl;
  thread_wait(9, 11);
  thread_broadcast(6, 2);
  thread_unlock(13);
  thread_yield();
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_wait(12, 1);
  cout << "2003761" << endl;
  thread_unlock(7);
  thread_signal(10, 8);
  thread_signal(0, 2);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(13, 7);
  cout << "2316264" << endl;
  thread_lock(10);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "2052577" << endl;
  thread_broadcast(1, 6);
  cout << "2243205" << endl;
  thread_signal(4, 1);
  thread_wait(11, 7);
  thread_broadcast(7, 10);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(6);
  thread_yield();
  thread_wait(10, 1);
  thread_lock(1);
  thread_signal(8, 11);
  thread_signal(3, 13);
  thread_signal(9, 4);
  thread_yield();
  thread_yield();
  cout << "770409" << endl;
  thread_yield();
  thread_lock(2);
  thread_wait(1, 7);
  thread_lock(11);
}

void xyz8(void* args) {
  thread_unlock(1);
  thread_signal(2, 2);
  thread_unlock(0);
  thread_yield();
  thread_lock(2);
  thread_lock(2);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_broadcast(0, 2);
  thread_broadcast(0, 2);
  thread_yield();
  thread_yield();
  thread_wait(1, 2);
  thread_broadcast(1, 1);
  thread_lock(1);
  thread_yield();
  thread_yield();
  thread_signal(1, 2);
  thread_yield();
  thread_wait(0, 1);
  thread_unlock(2);
}

void xyz9(void* args) {
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_wait(0, 0);
  thread_lock(1);
  thread_yield();
  thread_yield();
  cout << "328523" << endl;
  thread_yield();
  thread_broadcast(0, 0);
  thread_signal(0, 1);
  cout << "1825747" << endl;
  cout << "104643" << endl;
  thread_yield();
  thread_lock(1);
  cout << "1683949" << endl;
  cout << "678645" << endl;
  thread_yield();
  thread_unlock(0);
  thread_broadcast(1, 0);
  thread_signal(0, 0);
  thread_broadcast(1, 0);
  thread_yield();
  thread_lock(1);
  cout << "1486019" << endl;
  thread_unlock(1);
  cout << "239896" << endl;
  thread_yield();
  thread_signal(1, 0);
  thread_wait(1, 0);
  thread_yield();
  cout << "575625" << endl;
  thread_lock(0);
  thread_broadcast(0, 0);
  thread_yield();
  thread_yield();
  thread_broadcast(0, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_lock(1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_wait(1, 1);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  cout << "1979947" << endl;
  thread_yield();
  cout << "1717627" << endl;
  thread_broadcast(0, 1);
  thread_yield();
  thread_signal(0, 1);
  thread_wait(0, 0);
  thread_yield();
  thread_lock(0);
  cout << "1800339" << endl;
  thread_lock(1);
  cout << "2209993" << endl;
  thread_yield();
  thread_wait(1, 0);
  thread_signal(1, 0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_yield();
  thread_unlock(0);
  thread_unlock(1);
  thread_broadcast(0, 1);
  thread_yield();
  thread_yield();
  cout << "780395" << endl;
  thread_yield();
  thread_signal(1, 1);
  thread_yield();
  thread_signal(1, 1);
}

void xyz10(void* args) {
  thread_signal(0, 5);
  thread_yield();
  cout << "60195" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(1, 4);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(0, 5);
  thread_signal(2, 3);
  thread_lock(0);
  thread_signal(2, 1);
  thread_yield();
  thread_wait(3, 2);
  thread_yield();
  thread_unlock(4);
  cout << "5153" << endl;
  thread_wait(1, 5);
  thread_yield();
  thread_wait(0, 0);
  thread_yield();
  thread_wait(1, 1);
  cout << "67203" << endl;
  thread_yield();
  thread_yield();
  thread_signal(1, 3);
  thread_yield();
  thread_broadcast(0, 1);
  cout << "69598" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(2, 4);
  thread_signal(1, 5);
  thread_yield();
  thread_signal(1, 0);
  cout << "119917" << endl;
  thread_yield();
  cout << "54922" << endl;
  thread_signal(1, 2);
  thread_broadcast(1, 1);
  thread_broadcast(1, 3);
  cout << "102169" << endl;
  thread_lock(3);
  thread_signal(1, 1);
  thread_lock(1);
  thread_unlock(4);
  thread_yield();
  thread_broadcast(0, 2);
  thread_lock(1);
  thread_yield();
  thread_unlock(1);
  thread_lock(2);
  cout << "156773" << endl;
  thread_yield();
  thread_lock(0);
  cout << "64389" << endl;
}

void maker(void *args) {
  thread_create((thread_startfunc_t) xyz1, (void *) 100);
  thread_create((thread_startfunc_t) xyz2, (void *) 100);
  thread_yield();
  thread_broadcast(1, 1);
  thread_wait(1, 0);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(1, 1);
  thread_broadcast(1, 1);
  thread_create((thread_startfunc_t) xyz3, (void *) 100);
  thread_signal(1, 1);
  thread_create((thread_startfunc_t) xyz4, (void *) 100);
  thread_lock(1);
  thread_signal(0, 1);
  thread_yield();
  thread_broadcast(1, 1);
  thread_create((thread_startfunc_t) xyz5, (void *) 100);
  thread_lock(1);
  thread_create((thread_startfunc_t) xyz6, (void *) 100);
  thread_create((thread_startfunc_t) xyz7, (void *) 100);
  thread_create((thread_startfunc_t) xyz8, (void *) 100);
  thread_create((thread_startfunc_t) xyz9, (void *) 100);
  thread_wait(1, 1);
  thread_create((thread_startfunc_t) xyz10, (void *) 100);
  thread_unlock(1);
  thread_lock(1);
  thread_wait(1, 1);
  thread_wait(0, 0);
  thread_yield();
  thread_wait(0, 1);
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(0, 0);
  thread_yield();
  thread_unlock(0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(1, 1);
  thread_yield();
  thread_yield();
  thread_signal(0, 1);
  thread_unlock(0);
  thread_yield();
  thread_unlock(0);
  thread_lock(0);
  thread_yield();
  thread_unlock(0);
  thread_signal(1, 0);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_broadcast(1, 0);
  thread_unlock(1);
  thread_yield();
  thread_unlock(0);
  thread_lock(1);
  thread_yield();
  thread_yield();
  thread_signal(1, 1);
  thread_yield();
  thread_broadcast(1, 1);
  thread_yield();
  thread_broadcast(0, 1);
  thread_broadcast(1, 1);
  thread_yield();
  thread_yield();
  thread_broadcast(1, 0);
  thread_wait(1, 1);
  thread_yield();
  thread_yield();
  thread_signal(1, 1);
  thread_broadcast(1, 1);
  thread_signal(0, 1);
  thread_signal(0, 1);
  thread_broadcast(1, 0);
  thread_signal(0, 1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(0);
  thread_yield();
  thread_unlock(0);
  thread_broadcast(0, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_broadcast(1, 1);
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_broadcast(1, 0);
  thread_lock(0);
  thread_lock(0);
  thread_lock(1);
  thread_yield();
}

int main(int argc, char *argv[]) {
  thread_libinit((thread_startfunc_t)maker, &argc);
}
