#include <stdlib.h>
#include <iostream>
#include "thread.h"
#include <assert.h>
#include <vector>
#include <string.h>
#include <fstream>
using namespace std;

void xyz1(void* args);
void xyz2(void* args);
void xyz3(void* args);
void xyz4(void* args);
void xyz5(void* args);
void xyz6(void* args);
void xyz7(void* args) ;
void xyz8(void* args);
void xyz9(void* args);
void xyz10(void* args);
void maker(void *args);
void xyz1(void* args) {
  thread_lock(1);
  thread_signal(1, 0);
  thread_unlock(1);
  thread_broadcast(1, 1);
  thread_lock(0);
  thread_lock(0);
  thread_unlock(1);
  thread_yield();
  thread_unlock(1);
  thread_wait(1, 1);
  thread_unlock(0);
  thread_signal(1, 0);
  thread_unlock(1);
  thread_unlock(0);
  cout << "4231778" << endl;
  thread_wait(1, 1);
  thread_wait(0, 1);
  thread_signal(1, 1);
  thread_broadcast(0, 1);
  thread_unlock(1);
  thread_wait(1, 1);
  thread_lock(0);
  thread_signal(0, 0);
  thread_signal(0, 0);
  thread_lock(0);
  thread_lock(1);
  cout << "78301022" << endl;
  thread_unlock(0);
  thread_lock(1);
  thread_yield();
  thread_broadcast(1, 1);
  thread_unlock(1);
  thread_wait(1, 1);
  thread_unlock(1);
  thread_unlock(1);
  cout << "12135768" << endl;
  thread_signal(0, 0);
  thread_unlock(1);
  cout << "24214859" << endl;
  thread_yield();
  thread_yield();
  thread_unlock(0);
  cout << "122875675" << endl;
  thread_broadcast(0, 0);
  thread_wait(0, 0);
  thread_broadcast(0, 0);
  cout << "3084648" << endl;
  thread_signal(1, 1);
  thread_wait(1, 1);
  thread_lock(0);
  thread_lock(0);
  thread_signal(1, 0);
  cout << "3407959" << endl;
  cout << "113578077" << endl;
  thread_wait(1, 0);
  thread_yield();
  thread_yield();
  thread_broadcast(1, 0);
  cout << "110091003" << endl;
  cout << "24273042" << endl;
  thread_lock(0);
  cout << "112471658" << endl;
  thread_broadcast(0, 1);
  thread_signal(0, 0);
  thread_yield();
  thread_broadcast(1, 0);
  cout << "112021666" << endl;
  thread_broadcast(1, 0);
  cout << "10988442" << endl;
  thread_unlock(1);
  thread_wait(1, 1);
  thread_lock(0);
  thread_unlock(0);
  thread_lock(1);
  thread_signal(1, 1);
  thread_unlock(0);
  cout << "5300209" << endl;
  thread_lock(0);
  thread_unlock(0);
  thread_unlock(0);
  cout << "45414858" << endl;
  cout << "99034904" << endl;
  thread_unlock(1);
  thread_lock(1);
  thread_signal(1, 1);
  thread_lock(1);
  thread_lock(1);
  thread_wait(1, 0);
  thread_unlock(1);
  thread_wait(0, 0);
  thread_lock(0);
  thread_wait(1, 1);
  thread_unlock(0);
  thread_broadcast(0, 1);
  thread_yield();
  thread_signal(0, 1);
  thread_broadcast(1, 1);
  thread_lock(1);
  thread_broadcast(1, 1);
  thread_unlock(0);
  thread_wait(1, 1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_wait(0, 1);
  thread_yield();
  thread_lock(1);
  thread_lock(1);
  cout << "32231890" << endl;
  thread_lock(1);
  thread_wait(0, 1);
  thread_signal(0, 1);
  thread_lock(0);
  thread_broadcast(0, 1);
  thread_yield();
  thread_broadcast(0, 1);
  thread_wait(0, 0);
  cout << "22773629" << endl;
  thread_yield();
  thread_unlock(1);
  thread_broadcast(0, 1);
  thread_lock(0);
  thread_broadcast(0, 1);
  thread_unlock(1);
  thread_unlock(0);
  thread_signal(0, 0);
  thread_unlock(0);
  thread_broadcast(1, 1);
  thread_broadcast(1, 1);
  thread_yield();
  cout << "47340939" << endl;
  thread_wait(1, 1);
  thread_signal(0, 0);
  thread_broadcast(1, 0);
  thread_wait(0, 1);
  cout << "57487158" << endl;
  thread_lock(1);
  thread_wait(1, 0);
  thread_lock(1);
  thread_yield();
  thread_lock(1);
  cout << "90385593" << endl;
  thread_lock(1);
  thread_signal(1, 1);
  thread_lock(0);
  cout << "36295987" << endl;
  thread_broadcast(1, 0);
  thread_wait(0, 1);
  thread_yield();
  thread_unlock(1);
  thread_signal(1, 0);
  thread_yield();
  cout << "37877488" << endl;
  cout << "69201454" << endl;
}

void xyz2(void* args) {
  thread_yield();
  thread_lock(12);
  cout << "75093233" << endl;
  thread_signal(5, 11);
  cout << "40097755" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(10, 9);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "17389610" << endl;
  thread_yield();
  thread_wait(3, 3);
  thread_wait(0, 5);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_signal(2, 6);
  cout << "6256725" << endl;
  thread_lock(8);
  thread_broadcast(9, 2);
  thread_broadcast(1, 0);
  thread_lock(6);
  thread_broadcast(2, 1);
  thread_signal(9, 3);
  cout << "102141546" << endl;
  thread_broadcast(7, 1);
  thread_yield();
  thread_lock(5);
  thread_unlock(0);
  thread_wait(10, 2);
  thread_wait(3, 4);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(8, 4);
  thread_lock(10);
  thread_broadcast(12, 7);
  thread_unlock(1);
  thread_wait(6, 11);
  thread_signal(3, 11);
  thread_yield();
  thread_signal(1, 6);
  cout << "3120570" << endl;
  thread_lock(9);
  thread_unlock(9);
  thread_wait(0, 4);
  thread_yield();
  cout << "13724683" << endl;
  thread_yield();
  cout << "108046977" << endl;
  thread_wait(12, 4);
  thread_yield();
  thread_wait(6, 8);
  thread_yield();
  thread_yield();
  thread_broadcast(10, 10);
  thread_yield();
}

void xyz3(void* args) {
  thread_yield();
  thread_broadcast(0, 4);
  thread_lock(5);
  thread_signal(0, 0);
  thread_yield();
  thread_unlock(0);
  cout << "1720008" << endl;
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_wait(3, 4);
  thread_yield();
  thread_yield();
  thread_lock(6);
  thread_yield();
  thread_wait(3, 1);
  thread_signal(4, 5);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(4);
}

void xyz4(void* args) {
  thread_yield();
  thread_broadcast(1, 5);
  thread_yield();
  thread_yield();
  thread_wait(7, 2);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_unlock(3);
  thread_yield();
  thread_signal(3, 3);
  thread_unlock(0);
  thread_lock(0);
  cout << "18972197" << endl;
  thread_yield();
  thread_wait(8, 6);
  thread_signal(5, 0);
  thread_yield();
  thread_signal(6, 5);
  thread_yield();
  thread_lock(5);
  cout << "49715795" << endl;
  thread_lock(1);
  thread_broadcast(0, 3);
  thread_yield();
  thread_broadcast(4, 3);
  thread_lock(5);
  thread_lock(8);
  cout << "108902167" << endl;
  thread_yield();
  cout << "39991401" << endl;
  thread_wait(6, 6);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(6, 8);
  thread_wait(8, 5);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(0, 6);
  cout << "55594596" << endl;
  thread_yield();
  thread_yield();
  thread_signal(6, 7);
  thread_yield();
  thread_wait(0, 7);
  thread_yield();
  thread_signal(5, 8);
  thread_yield();
  thread_signal(8, 1);
  thread_broadcast(4, 6);
}

void xyz5(void* args) {
  thread_yield();
  thread_signal(3, 16);
  thread_unlock(5);
  thread_yield();
  thread_broadcast(2, 0);
  thread_yield();
  thread_signal(4, 3);
  thread_yield();
  thread_yield();
  thread_signal(4, 13);
  thread_broadcast(8, 3);
  thread_yield();
  thread_unlock(18);
  thread_unlock(6);
  cout << "487330" << endl;
  thread_yield();
  thread_broadcast(1, 13);
  thread_yield();
  thread_yield();
  thread_broadcast(6, 13);
  thread_lock(5);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(12);
  thread_yield();
  thread_lock(18);
  thread_yield();
  cout << "429802" << endl;
  thread_wait(2, 11);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(14, 8);
  thread_yield();
  thread_unlock(2);
  thread_yield();
  thread_unlock(10);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(6, 8);
  thread_yield();
  thread_wait(4, 0);
  thread_yield();
  thread_signal(0, 17);
  thread_yield();
  thread_unlock(18);
  thread_wait(14, 12);
  thread_yield();
  thread_unlock(6);
  thread_yield();
  thread_yield();
  thread_wait(14, 10);
  thread_signal(3, 15);
  thread_lock(17);
  thread_unlock(14);
  thread_yield();
  thread_signal(2, 15);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(9, 14);
  thread_lock(13);
  thread_yield();
  thread_signal(15, 14);
  thread_lock(7);
  thread_yield();
  thread_unlock(18);
  thread_yield();
  thread_wait(11, 12);
  thread_signal(10, 16);
  thread_broadcast(6, 5);
  thread_broadcast(9, 7);
  thread_yield();
  thread_lock(10);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "1078087" << endl;
  thread_broadcast(3, 14);
  thread_yield();
  thread_signal(6, 1);
  cout << "563059" << endl;
  thread_signal(14, 7);
  thread_wait(2, 2);
  cout << "290330" << endl;
  thread_unlock(16);
  thread_signal(16, 14);
  thread_unlock(0);
  thread_lock(7);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(18, 0);
  thread_unlock(16);
  thread_broadcast(15, 4);
  thread_yield();
  thread_broadcast(7, 15);
  thread_unlock(18);
  thread_yield();
  thread_broadcast(13, 10);
  thread_yield();
  thread_yield();
  thread_unlock(3);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(16);
  thread_signal(16, 18);
  cout << "990673" << endl;
  thread_yield();
  thread_yield();
  thread_broadcast(9, 18);
  thread_yield();
  thread_yield();
  thread_wait(15, 11);
  thread_yield();
  thread_signal(18, 15);
  thread_signal(4, 8);
  cout << "1233296" << endl;
}

void xyz6(void* args) {
  thread_unlock(2);
  thread_signal(2, 2);
  thread_lock(3);
  thread_yield();
  cout << "458725" << endl;
  thread_wait(3, 0);
  thread_unlock(2);
  thread_signal(0, 0);
  thread_signal(3, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "36942" << endl;
  thread_yield();
  thread_signal(2, 0);
  cout << "471390" << endl;
  thread_yield();
  thread_broadcast(2, 3);
  thread_unlock(2);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(2);
  thread_yield();
  cout << "932654" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 0);
  thread_yield();
  thread_unlock(0);
  thread_signal(3, 0);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_yield();
  cout << "1011609" << endl;
  thread_broadcast(3, 0);
  thread_yield();
  thread_unlock(2);
  thread_unlock(1);
}

void xyz7(void* args) {
  thread_yield();
  thread_wait(11, 4);
  thread_unlock(0);
  thread_broadcast(0, 0);
  thread_yield();
  thread_lock(0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(4, 12);
  thread_broadcast(5, 12);
  thread_lock(13);
  thread_yield();
  thread_broadcast(13, 10);
  thread_lock(3);
  thread_unlock(10);
  thread_lock(9);
  thread_lock(9);
  thread_yield();
  thread_wait(3, 11);
  thread_yield();
  thread_lock(7);
  thread_lock(11);
  thread_wait(3, 4);
  thread_yield();
  thread_signal(13, 10);
  thread_broadcast(10, 7);
  thread_yield();
  thread_yield();
  thread_unlock(2);
  thread_unlock(1);
  thread_lock(5);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "1548901" << endl;
  thread_yield();
  thread_broadcast(4, 2);
  thread_yield();
  thread_lock(10);
  thread_yield();
  thread_signal(1, 3);
  thread_wait(7, 10);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(11, 13);
  thread_signal(12, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "266379" << endl;
  thread_signal(12, 6);
  thread_yield();
  thread_wait(13, 1);
  cout << "622927" << endl;
  cout << "1399460" << endl;
  thread_signal(7, 4);
  thread_lock(11);
  thread_wait(6, 9);
  thread_yield();
  thread_wait(0, 1);
  thread_wait(8, 10);
  thread_signal(6, 5);
  thread_lock(3);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_lock(4);
  thread_wait(5, 1);
  thread_lock(7);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(4);
  thread_wait(8, 3);
  thread_yield();
  thread_broadcast(5, 10);
  thread_yield();
  thread_wait(12, 10);
  thread_lock(5);
  thread_signal(9, 5);
  thread_signal(3, 4);
  thread_wait(2, 0);
  thread_wait(8, 8);
  thread_yield();
  thread_yield();
  thread_broadcast(4, 12);
}

void xyz8(void* args) {
  thread_signal(0, 0);
  thread_broadcast(1, 1);
  thread_yield();
  thread_yield();
  thread_signal(2, 1);
  thread_lock(0);
  cout << "19931" << endl;
  thread_yield();
  thread_signal(0, 1);
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_wait(2, 0);
  thread_unlock(1);
  thread_wait(2, 1);
  thread_lock(1);
  thread_wait(1, 1);
  thread_yield();
  thread_yield();
}

void xyz9(void* args) {
  cout << "637381" << endl;
  thread_broadcast(0, 0);
  thread_yield();
  thread_wait(0, 1);
  thread_yield();
  thread_signal(1, 1);
  thread_wait(0, 0);
  thread_unlock(0);
  thread_yield();
  thread_lock(0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_signal(1, 1);
  cout << "1776449" << endl;
  thread_lock(0);
  thread_signal(0, 1);
  thread_lock(1);
  thread_signal(1, 1);
  thread_yield();
  thread_broadcast(1, 1);
  thread_wait(1, 1);
  thread_wait(0, 0);
  thread_broadcast(1, 1);
  thread_yield();
  thread_broadcast(0, 0);
  thread_lock(0);
  thread_yield();
  thread_broadcast(0, 1);
  thread_broadcast(0, 0);
  thread_yield();
  thread_wait(1, 1);
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_lock(1);
  thread_broadcast(0, 0);
  thread_yield();
  thread_yield();
  cout << "1012150" << endl;
  thread_yield();
  thread_broadcast(1, 1);
  thread_yield();
  thread_broadcast(0, 1);
  thread_yield();
  thread_lock(0);
  thread_wait(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "609688" << endl;
  thread_wait(1, 0);
  thread_unlock(0);
  thread_wait(0, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(0, 0);
  thread_unlock(0);
  thread_wait(1, 0);
  thread_yield();
  thread_unlock(0);
  thread_yield();
  thread_unlock(0);
  cout << "1344231" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(1, 1);
  thread_broadcast(0, 0);
  thread_yield();
  thread_yield();
  thread_yield();
}

void xyz10(void* args) {
  thread_wait(3, 1);
  cout << "98288" << endl;
  thread_wait(4, 5);
  thread_yield();
  thread_yield();
  thread_unlock(0);
  thread_unlock(4);
  thread_unlock(2);
  thread_broadcast(3, 5);
  thread_signal(4, 3);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(3, 3);
  thread_unlock(1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(3, 4);
  thread_yield();
  thread_broadcast(2, 0);
  thread_unlock(2);
  thread_broadcast(0, 3);
  thread_unlock(2);
  thread_wait(1, 3);
  thread_wait(4, 5);
  thread_signal(1, 5);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_broadcast(4, 3);
  thread_unlock(4);
  thread_signal(3, 4);
  thread_signal(3, 5);
  thread_lock(2);
  thread_unlock(1);
  thread_yield();
  thread_broadcast(2, 2);
  thread_yield();
  thread_yield();
  cout << "198513" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_signal(1, 3);
  thread_yield();
  thread_broadcast(2, 0);
  thread_broadcast(1, 4);
  thread_yield();
  cout << "174380" << endl;
  thread_yield();
  cout << "148874" << endl;
  thread_unlock(3);
}

void maker(void *args) {
  thread_lock(0);
  thread_lock(1);
  thread_signal(0, 0);
  thread_create((thread_startfunc_t) xyz1, (void *) 100);
  thread_create((thread_startfunc_t) xyz2, (void *) 100);
  thread_create((thread_startfunc_t) xyz3, (void *) 100);
  thread_create((thread_startfunc_t) xyz4, (void *) 100);
  thread_yield();
  thread_broadcast(0, 1);
  thread_unlock(0);
  thread_wait(0, 0);
  thread_broadcast(0, 1);
  thread_lock(1);
  thread_create((thread_startfunc_t) xyz5, (void *) 100);
  thread_broadcast(1, 1);
  thread_yield();
  thread_wait(0, 0);
  thread_create((thread_startfunc_t) xyz6, (void *) 100);
  thread_lock(1);
  thread_create((thread_startfunc_t) xyz7, (void *) 100);
  thread_create((thread_startfunc_t) xyz8, (void *) 100);
  thread_create((thread_startfunc_t) xyz9, (void *) 100);
  thread_signal(1, 1);
  thread_create((thread_startfunc_t) xyz10, (void *) 100);
  thread_yield();
  thread_lock(1);
  thread_signal(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 1);
  thread_signal(0, 0);
  thread_signal(0, 1);
  thread_wait(0, 0);
  thread_signal(1, 0);
  thread_yield();
  thread_wait(1, 0);
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_signal(0, 1);
  thread_signal(1, 0);
  thread_wait(0, 0);
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(0, 0);
  thread_yield();
  thread_yield();
  thread_wait(1, 0);
  thread_yield();
  thread_unlock(0);
  thread_unlock(0);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_yield();
  thread_broadcast(1, 0);
  thread_yield();
  thread_signal(0, 1);
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_unlock(1);
  thread_lock(1);
  thread_yield();
  thread_broadcast(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_unlock(1);
  thread_broadcast(0, 0);
  thread_lock(0);
  thread_broadcast(1, 0);
  thread_unlock(0);
  thread_signal(1, 1);
  thread_broadcast(0, 0);
  thread_unlock(0);
  thread_yield();
  thread_yield();
  thread_unlock(0);
  thread_signal(1, 1);
  thread_wait(1, 1);
  thread_lock(1);
  thread_yield();
  thread_broadcast(1, 0);
  thread_wait(0, 1);
  thread_wait(0, 1);
  thread_yield();
  thread_yield();
  thread_wait(0, 1);
  thread_lock(0);
  thread_wait(1, 0);
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_yield();
}

int main(int argc, char *argv[]) {
  thread_libinit((thread_startfunc_t)maker, &argc);
}
