#include <stdlib.h>
#include <iostream>
#include "thread.h"
#include <assert.h>
#include <vector>
#include <string.h>
#include <fstream>
using namespace std;

void xyz1(void* args);
void xyz2(void* args);
void xyz3(void* args);
void xyz4(void* args);
void xyz5(void* args);
void xyz6(void* args);
void xyz7(void* args) ;
void xyz8(void* args);
void xyz9(void* args);
void xyz10(void* args);
void maker(void *args);
void xyz1(void* args) {
  thread_yield();
  thread_broadcast(1, 1);
  thread_signal(1, 1);
  thread_wait(1, 1);
  cout << "69498890" << endl;
  thread_signal(1, 1);
  thread_lock(0);
  thread_wait(1, 0);
  thread_broadcast(0, 1);
  thread_broadcast(0, 1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_lock(1);
  thread_yield();
  thread_broadcast(1, 0);
  thread_unlock(1);
  thread_signal(0, 1);
  cout << "30420047" << endl;
  thread_unlock(0);
  thread_wait(0, 0);
  thread_signal(0, 1);
  thread_lock(1);
  cout << "74303427" << endl;
  thread_broadcast(0, 0);
  thread_wait(1, 0);
  cout << "77993574" << endl;
  thread_wait(1, 1);
  thread_broadcast(0, 1);
  thread_signal(0, 0);
  cout << "57986107" << endl;
  thread_yield();
  thread_wait(0, 0);
  thread_unlock(0);
  thread_signal(1, 1);
  thread_lock(0);
  thread_unlock(1);
  thread_broadcast(1, 1);
  thread_unlock(1);
  thread_signal(0, 1);
  thread_wait(0, 0);
  thread_signal(1, 0);
  thread_wait(0, 1);
  thread_wait(1, 0);
  cout << "25030861" << endl;
  thread_wait(1, 0);
  thread_unlock(0);
  thread_lock(1);
  thread_yield();
  thread_lock(0);
  thread_broadcast(1, 0);
  thread_yield();
  thread_unlock(0);
  thread_unlock(1);
  thread_wait(0, 0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_broadcast(1, 0);
  thread_unlock(1);
  thread_broadcast(1, 0);
  thread_lock(0);
  thread_wait(1, 0);
  thread_wait(0, 1);
  thread_lock(1);
  thread_broadcast(1, 1);
  thread_broadcast(0, 1);
  thread_wait(0, 0);
  thread_wait(0, 0);
  thread_unlock(0);
  thread_wait(0, 0);
  thread_broadcast(0, 0);
  thread_lock(0);
  thread_broadcast(0, 1);
  thread_unlock(1);
  thread_broadcast(1, 0);
  cout << "115401758" << endl;
  thread_yield();
  cout << "116083863" << endl;
  thread_signal(1, 1);
  thread_unlock(0);
  cout << "98879883" << endl;
  thread_signal(0, 1);
  cout << "113244176" << endl;
  cout << "117842811" << endl;
  thread_lock(0);
  thread_wait(1, 1);
  thread_broadcast(0, 1);
  thread_wait(1, 0);
  thread_wait(0, 1);
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_wait(1, 0);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(0);
  thread_lock(0);
  cout << "66960985" << endl;
  thread_lock(1);
  thread_broadcast(1, 0);
  thread_unlock(1);
  thread_broadcast(0, 1);
  thread_broadcast(1, 0);
  thread_lock(0);
  thread_lock(1);
  thread_wait(0, 1);
  thread_signal(1, 1);
  thread_unlock(0);
  thread_wait(0, 1);
  cout << "78024155" << endl;
  thread_broadcast(1, 1);
  cout << "3193969" << endl;
  thread_broadcast(0, 0);
  thread_wait(0, 1);
  thread_unlock(1);
  cout << "10824098" << endl;
  thread_wait(1, 1);
  thread_lock(1);
  thread_signal(1, 1);
  thread_yield();
  thread_lock(1);
  thread_broadcast(1, 1);
  thread_lock(0);
  thread_lock(0);
  thread_lock(0);
  thread_signal(0, 1);
  thread_unlock(1);
  thread_broadcast(1, 0);
  thread_lock(0);
  thread_broadcast(0, 1);
  thread_wait(0, 0);
  thread_yield();
  thread_broadcast(1, 1);
  thread_lock(1);
  thread_broadcast(0, 0);
  thread_signal(0, 1);
  thread_unlock(0);
  thread_broadcast(0, 1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(1, 1);
  thread_signal(0, 1);
  thread_broadcast(1, 1);
  thread_lock(1);
  thread_lock(0);
  thread_yield();
  thread_unlock(1);
  thread_yield();
  cout << "85415310" << endl;
  thread_wait(0, 1);
  thread_broadcast(1, 0);
  cout << "123294324" << endl;
  cout << "12608639" << endl;
  thread_wait(0, 0);
  thread_yield();
  thread_wait(0, 0);
  thread_broadcast(1, 1);
  thread_signal(1, 1);
}

void xyz2(void* args) {
  thread_signal(8, 0);
  thread_wait(5, 7);
  thread_yield();
  cout << "83170120" << endl;
  thread_yield();
  cout << "77766498" << endl;
  thread_broadcast(10, 12);
  thread_lock(11);
  thread_yield();
  thread_signal(4, 1);
  thread_wait(7, 6);
  thread_signal(0, 1);
  thread_yield();
  thread_signal(9, 10);
  thread_yield();
  cout << "76847734" << endl;
  thread_yield();
  cout << "91413665" << endl;
  thread_yield();
  thread_yield();
  thread_unlock(4);
  thread_yield();
  thread_broadcast(11, 5);
  thread_broadcast(3, 8);
  cout << "83311110" << endl;
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_broadcast(9, 7);
  thread_yield();
  thread_yield();
  thread_wait(4, 5);
  thread_yield();
  thread_unlock(5);
  thread_yield();
  thread_yield();
  thread_lock(12);
  thread_yield();
  thread_unlock(5);
  thread_signal(8, 9);
  thread_yield();
  thread_unlock(8);
  cout << "120677850" << endl;
  thread_yield();
  thread_lock(8);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_lock(3);
  thread_broadcast(1, 3);
  cout << "95258777" << endl;
  thread_broadcast(12, 11);
  thread_lock(7);
  thread_lock(8);
  thread_lock(11);
  thread_yield();
  thread_signal(8, 3);
  cout << "108552842" << endl;
  thread_broadcast(2, 1);
  thread_yield();
  thread_yield();
  thread_signal(5, 11);
  thread_signal(10, 0);
}

void xyz3(void* args) {
  thread_broadcast(1, 0);
  thread_yield();
  thread_yield();
  thread_signal(4, 1);
  thread_signal(4, 0);
  thread_signal(5, 0);
  thread_yield();
  thread_unlock(5);
  thread_unlock(2);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(6, 6);
  thread_yield();
  cout << "11237715" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(2, 1);
  thread_lock(4);
  thread_broadcast(6, 3);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(2, 5);
  thread_yield();
}

void xyz4(void* args) {
  cout << "4840558" << endl;
  thread_lock(7);
  thread_signal(1, 1);
  thread_signal(5, 3);
  thread_signal(2, 7);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(1, 2);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(5, 3);
  thread_signal(2, 5);
  cout << "52499826" << endl;
  thread_yield();
  thread_broadcast(0, 4);
  thread_yield();
  thread_broadcast(3, 4);
  thread_wait(4, 1);
  cout << "47179903" << endl;
  cout << "56136143" << endl;
  thread_wait(3, 5);
  thread_yield();
  thread_signal(1, 5);
  thread_yield();
  thread_signal(4, 5);
  cout << "99664600" << endl;
  cout << "99809169" << endl;
  thread_broadcast(6, 0);
  thread_yield();
  thread_signal(8, 4);
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_broadcast(0, 1);
  thread_yield();
  thread_yield();
  thread_broadcast(8, 4);
  thread_lock(1);
  thread_broadcast(2, 8);
  thread_broadcast(8, 4);
  thread_signal(3, 4);
  thread_unlock(3);
  cout << "119001765" << endl;
  thread_signal(8, 1);
  thread_yield();
  thread_unlock(7);
  thread_wait(0, 2);
  thread_signal(6, 4);
  cout << "62332354" << endl;
  thread_yield();
  thread_yield();
}

void xyz5(void* args) {
  thread_lock(18);
  thread_yield();
  thread_lock(15);
  thread_broadcast(16, 17);
  thread_yield();
  thread_lock(7);
  thread_wait(4, 8);
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(18);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(5, 15);
  thread_wait(2, 0);
  thread_wait(3, 12);
  thread_yield();
  thread_broadcast(3, 12);
  cout << "915604" << endl;
  thread_signal(13, 14);
  thread_broadcast(14, 3);
  thread_unlock(7);
  cout << "1025411" << endl;
  thread_signal(11, 15);
  thread_signal(8, 14);
  cout << "691632" << endl;
  thread_wait(8, 0);
  thread_yield();
  thread_lock(11);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(7, 15);
  thread_signal(13, 12);
  thread_yield();
  thread_broadcast(3, 12);
  thread_yield();
  thread_signal(6, 1);
  cout << "699263" << endl;
  thread_wait(2, 4);
  thread_unlock(11);
  cout << "253693" << endl;
  cout << "710606" << endl;
  thread_wait(13, 15);
  thread_signal(18, 3);
  thread_signal(11, 6);
  thread_lock(7);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(10, 10);
  thread_yield();
  thread_wait(1, 1);
  thread_yield();
  thread_yield();
  cout << "1163396" << endl;
  thread_yield();
  thread_lock(15);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_lock(6);
  thread_yield();
  thread_wait(1, 17);
  thread_signal(11, 17);
  thread_signal(17, 18);
  thread_unlock(12);
  thread_yield();
  cout << "853559" << endl;
  thread_signal(13, 10);
  thread_yield();
  cout << "239344" << endl;
  thread_yield();
  thread_wait(13, 6);
  thread_yield();
  thread_yield();
  cout << "837806" << endl;
  thread_unlock(2);
  thread_unlock(16);
  thread_yield();
  thread_wait(8, 6);
  thread_yield();
  thread_broadcast(2, 15);
  thread_wait(16, 11);
  thread_broadcast(18, 18);
  thread_wait(18, 12);
  thread_lock(3);
  thread_yield();
  thread_unlock(2);
  thread_broadcast(7, 15);
  thread_wait(3, 6);
  cout << "1023395" << endl;
  thread_lock(14);
  thread_yield();
  thread_wait(9, 6);
  thread_yield();
  thread_yield();
  thread_broadcast(9, 2);
  thread_signal(18, 8);
  thread_unlock(12);
  cout << "876642" << endl;
  thread_yield();
  thread_broadcast(10, 0);
  thread_wait(13, 1);
  thread_lock(14);
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_signal(13, 15);
  thread_unlock(12);
  thread_lock(13);
  thread_unlock(12);
  thread_lock(11);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(16);
  thread_lock(1);
  thread_wait(4, 11);
  thread_lock(4);
  thread_broadcast(0, 18);
  thread_broadcast(7, 0);
  thread_broadcast(0, 10);
  thread_yield();
}

void xyz6(void* args) {
  thread_yield();
  thread_broadcast(2, 2);
  thread_broadcast(0, 2);
  thread_wait(0, 2);
  thread_lock(0);
  thread_wait(3, 1);
  thread_lock(0);
  thread_yield();
  thread_unlock(0);
  cout << "716503" << endl;
  cout << "369521" << endl;
  cout << "528721" << endl;
  cout << "166625" << endl;
  thread_lock(3);
  thread_yield();
  thread_lock(0);
  thread_signal(1, 1);
  thread_broadcast(1, 2);
  cout << "526272" << endl;
  thread_unlock(0);
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_broadcast(2, 2);
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_unlock(3);
  thread_broadcast(2, 2);
  thread_yield();
  thread_yield();
  thread_wait(0, 3);
  thread_signal(3, 1);
  thread_wait(0, 2);
  thread_yield();
  cout << "488935" << endl;
  thread_broadcast(0, 1);
  thread_wait(0, 2);
  thread_wait(1, 2);
  thread_signal(3, 1);
  thread_unlock(1);
  thread_wait(0, 3);
}

void xyz7(void* args) {
  thread_wait(8, 3);
  thread_wait(1, 4);
  thread_unlock(6);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(13);
  thread_yield();
  thread_lock(1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_lock(6);
  thread_broadcast(13, 1);
  thread_yield();
  thread_lock(9);
  thread_wait(8, 9);
  thread_unlock(11);
  thread_lock(1);
  thread_unlock(4);
  thread_yield();
  thread_signal(7, 13);
  thread_broadcast(4, 3);
  cout << "30215" << endl;
  thread_wait(5, 11);
  thread_wait(11, 3);
  cout << "898095" << endl;
  cout << "2099500" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(5, 7);
  thread_yield();
  thread_broadcast(11, 10);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(1, 6);
  thread_signal(4, 8);
  thread_lock(7);
  thread_lock(5);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "1826965" << endl;
  thread_wait(12, 0);
  thread_unlock(9);
  thread_wait(0, 9);
  thread_wait(13, 13);
  cout << "1871742" << endl;
  thread_wait(4, 12);
  thread_unlock(7);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(13, 10);
  thread_yield();
  thread_lock(10);
  thread_broadcast(5, 0);
  thread_signal(0, 7);
  thread_signal(9, 3);
  thread_lock(3);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(5, 11);
  thread_yield();
  thread_unlock(11);
  thread_wait(12, 10);
  thread_unlock(1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_signal(7, 13);
  thread_broadcast(5, 12);
  thread_lock(4);
  thread_signal(2, 1);
  thread_yield();
  cout << "2700796" << endl;
  thread_wait(11, 10);
  thread_wait(12, 8);
  thread_wait(0, 1);
  thread_broadcast(11, 1);
  thread_unlock(6);
  thread_yield();
  thread_lock(1);
  cout << "2853428" << endl;
  cout << "1427408" << endl;
  thread_yield();
  thread_yield();
  cout << "2970070" << endl;
  thread_yield();
  thread_lock(6);
  thread_yield();
}

void xyz8(void* args) {
  thread_wait(1, 0);
  thread_yield();
  thread_lock(1);
  thread_unlock(2);
  thread_unlock(2);
  thread_signal(1, 0);
  thread_yield();
  thread_unlock(1);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(2, 0);
  thread_yield();
  thread_signal(2, 0);
  cout << "21720" << endl;
  thread_unlock(0);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_unlock(1);
  thread_broadcast(2, 0);
}

void xyz9(void* args) {
  thread_wait(0, 0);
  thread_lock(1);
  thread_lock(1);
  thread_unlock(1);
  thread_yield();
  thread_broadcast(1, 0);
  thread_lock(0);
  thread_yield();
  thread_yield();
  cout << "901886" << endl;
  cout << "2147590" << endl;
  thread_unlock(1);
  thread_yield();
  cout << "1733943" << endl;
  thread_broadcast(1, 1);
  thread_wait(1, 0);
  thread_wait(1, 0);
  thread_yield();
  thread_unlock(1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_broadcast(0, 1);
  thread_unlock(1);
  cout << "2164878" << endl;
  thread_yield();
  thread_signal(0, 0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 0);
  thread_yield();
  thread_signal(0, 1);
  thread_unlock(0);
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_broadcast(1, 1);
  thread_wait(1, 1);
  thread_signal(1, 0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(1);
  thread_yield();
  thread_broadcast(1, 0);
  thread_signal(0, 1);
  cout << "1998384" << endl;
  cout << "1844224" << endl;
  thread_yield();
  thread_yield();
  thread_broadcast(1, 1);
  thread_broadcast(0, 0);
  thread_signal(1, 1);
  thread_yield();
  cout << "1529112" << endl;
  thread_wait(0, 1);
  thread_yield();
  thread_signal(0, 1);
  cout << "810181" << endl;
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_wait(0, 0);
  thread_unlock(0);
  thread_unlock(0);
  thread_unlock(0);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(1, 1);
  thread_unlock(0);
  thread_unlock(1);
  thread_yield();
  thread_yield();
  cout << "1779601" << endl;
  thread_yield();
  thread_broadcast(1, 0);
  thread_wait(0, 1);
  thread_yield();
  thread_wait(1, 1);
  thread_wait(1, 1);
}

void xyz10(void* args) {
  thread_yield();
  thread_wait(4, 5);
  thread_lock(1);
  thread_wait(0, 2);
  thread_signal(0, 1);
  thread_signal(0, 2);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(1, 2);
  thread_broadcast(3, 2);
  thread_yield();
  thread_lock(3);
  thread_yield();
  thread_yield();
  thread_broadcast(0, 2);
  cout << "109125" << endl;
  thread_yield();
  thread_wait(1, 4);
  thread_signal(1, 5);
  thread_yield();
  thread_lock(0);
  thread_signal(1, 4);
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_broadcast(2, 3);
  thread_yield();
  thread_unlock(4);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(3, 0);
  thread_yield();
  thread_broadcast(3, 1);
  cout << "53229" << endl;
  thread_unlock(3);
  thread_lock(1);
  thread_yield();
  thread_signal(2, 0);
  thread_broadcast(1, 3);
  thread_yield();
  cout << "172527" << endl;
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_lock(2);
  thread_yield();
  thread_unlock(0);
  thread_yield();
  thread_lock(1);
  thread_broadcast(1, 2);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(2, 1);
  thread_lock(1);
  thread_yield();
  thread_broadcast(1, 3);
  thread_yield();
  thread_lock(3);
}

void maker(void *args) {
  thread_create((thread_startfunc_t) xyz1, (void *) 100);
  thread_lock(0);
  thread_broadcast(1, 0);
  thread_signal(1, 1);
  thread_signal(0, 1);
  thread_create((thread_startfunc_t) xyz2, (void *) 100);
  thread_wait(0, 0);
  thread_yield();
  thread_create((thread_startfunc_t) xyz3, (void *) 100);
  thread_create((thread_startfunc_t) xyz4, (void *) 100);
  thread_create((thread_startfunc_t) xyz5, (void *) 100);
  thread_unlock(1);
  thread_create((thread_startfunc_t) xyz6, (void *) 100);
  thread_lock(1);
  thread_create((thread_startfunc_t) xyz7, (void *) 100);
  thread_create((thread_startfunc_t) xyz8, (void *) 100);
  thread_create((thread_startfunc_t) xyz9, (void *) 100);
  thread_create((thread_startfunc_t) xyz10, (void *) 100);
  thread_wait(1, 0);
  thread_yield();
  thread_lock(1);
  thread_signal(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_broadcast(1, 0);
  thread_lock(1);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_signal(1, 1);
  thread_yield();
  thread_signal(0, 1);
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_broadcast(1, 1);
  thread_wait(0, 1);
  thread_unlock(0);
  thread_unlock(0);
  thread_unlock(1);
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_broadcast(0, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 1);
  thread_signal(1, 1);
  thread_wait(1, 0);
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_yield();
  thread_broadcast(0, 1);
  thread_wait(1, 0);
  thread_lock(0);
  thread_unlock(1);
  thread_signal(0, 0);
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_broadcast(0, 1);
  thread_lock(1);
  thread_signal(0, 1);
  thread_yield();
  thread_wait(0, 1);
  thread_broadcast(1, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_lock(0);
  thread_signal(0, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(0, 0);
  thread_unlock(0);
  thread_signal(1, 0);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_unlock(1);
}

int main(int argc, char *argv[]) {
  thread_libinit((thread_startfunc_t)maker, &argc);
}
