#include <stdlib.h>
#include <iostream>
#include "thread.h"
#include <assert.h>
#include <vector>
#include <string.h>
#include <fstream>
using namespace std;

void xyz1(void* args);
void xyz2(void* args);
void xyz3(void* args);
void xyz4(void* args);
void xyz5(void* args);
void xyz6(void* args);
void xyz7(void* args) ;
void xyz8(void* args);
void xyz9(void* args);
void xyz10(void* args);
void maker(void *args);
void xyz1(void* args) {
  cout << "64321941" << endl;
  thread_unlock(0);
  thread_yield();
  thread_broadcast(1, 0);
  cout << "36956651" << endl;
  thread_wait(0, 0);
  thread_broadcast(0, 0);
  thread_yield();
  cout << "61593254" << endl;
  cout << "87583935" << endl;
  thread_signal(1, 0);
  thread_wait(0, 1);
  thread_unlock(0);
  thread_wait(1, 1);
  thread_wait(0, 0);
  thread_broadcast(1, 1);
  thread_unlock(0);
  cout << "10445344" << endl;
  thread_unlock(1);
  thread_lock(1);
  cout << "32059088" << endl;
  thread_broadcast(1, 0);
  thread_unlock(0);
  thread_signal(0, 1);
  thread_wait(0, 0);
  thread_yield();
  thread_lock(1);
  thread_signal(1, 1);
  thread_unlock(0);
  cout << "12659872" << endl;
  thread_wait(1, 0);
  thread_wait(0, 1);
  thread_wait(1, 0);
  thread_unlock(1);
  thread_yield();
  thread_yield();
  thread_wait(0, 1);
  thread_wait(1, 0);
  thread_lock(1);
  cout << "77064118" << endl;
  thread_unlock(0);
  thread_unlock(1);
  thread_wait(1, 1);
  thread_unlock(0);
  thread_signal(1, 1);
  cout << "2068032" << endl;
  thread_lock(0);
  thread_lock(1);
  cout << "55514376" << endl;
  thread_unlock(0);
  thread_lock(1);
  thread_lock(1);
  thread_broadcast(0, 0);
  thread_lock(1);
  cout << "16339452" << endl;
  thread_broadcast(1, 1);
  thread_yield();
  thread_unlock(0);
  thread_signal(1, 1);
  thread_yield();
  thread_lock(0);
  thread_broadcast(1, 1);
  thread_signal(0, 1);
  thread_unlock(1);
  cout << "88516833" << endl;
  thread_signal(0, 1);
  thread_lock(0);
  thread_unlock(0);
  thread_unlock(1);
  cout << "16747299" << endl;
  thread_lock(0);
  cout << "12109321" << endl;
  thread_broadcast(0, 0);
  thread_broadcast(1, 0);
  thread_wait(0, 0);
  thread_yield();
  cout << "15463835" << endl;
  thread_wait(0, 1);
  thread_signal(1, 1);
  thread_broadcast(1, 0);
  thread_wait(0, 0);
  thread_yield();
  thread_broadcast(0, 0);
  thread_signal(1, 1);
  thread_lock(1);
  thread_unlock(1);
  thread_unlock(0);
  thread_lock(1);
  thread_lock(1);
  thread_signal(0, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_wait(0, 0);
  thread_unlock(0);
  thread_unlock(1);
  thread_yield();
  cout << "18703149" << endl;
  thread_lock(0);
  thread_signal(1, 1);
  thread_unlock(1);
  thread_lock(1);
  thread_wait(1, 1);
  cout << "21951792" << endl;
  thread_wait(0, 1);
  thread_yield();
  thread_broadcast(0, 1);
  cout << "62903506" << endl;
  thread_unlock(1);
  thread_wait(1, 0);
  cout << "24646534" << endl;
  thread_broadcast(1, 0);
  thread_lock(1);
  thread_unlock(0);
  thread_broadcast(0, 0);
  thread_wait(1, 1);
  cout << "113735137" << endl;
  thread_signal(0, 1);
  thread_signal(1, 0);
  thread_yield();
  cout << "65730247" << endl;
  thread_lock(1);
  thread_broadcast(0, 0);
  thread_signal(0, 1);
  thread_wait(1, 0);
  thread_lock(0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(0);
  thread_wait(1, 0);
  thread_broadcast(0, 0);
  thread_lock(0);
  thread_unlock(1);
  cout << "73444037" << endl;
  thread_wait(0, 1);
  thread_signal(0, 1);
  thread_signal(1, 1);
  thread_signal(1, 0);
  thread_unlock(0);
  thread_broadcast(0, 1);
  thread_yield();
  thread_unlock(0);
  thread_unlock(1);
  thread_lock(0);
  cout << "70249170" << endl;
  thread_wait(0, 1);
  thread_unlock(1);
  thread_unlock(0);
  thread_unlock(0);
  cout << "117875899" << endl;
}

void xyz2(void* args) {
  thread_yield();
  thread_lock(2);
  thread_broadcast(12, 11);
  thread_unlock(11);
  thread_broadcast(5, 8);
  thread_yield();
  thread_signal(10, 8);
  thread_wait(0, 12);
  thread_broadcast(11, 7);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 10);
  thread_yield();
  thread_wait(10, 8);
  thread_lock(8);
  thread_signal(3, 7);
  thread_yield();
  thread_unlock(1);
  thread_broadcast(6, 2);
  thread_yield();
  cout << "25680304" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(6);
  thread_yield();
  thread_yield();
  thread_wait(3, 1);
  thread_broadcast(5, 10);
  thread_lock(10);
  thread_yield();
  thread_yield();
  thread_broadcast(3, 10);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(6, 6);
  cout << "66295801" << endl;
  thread_yield();
  thread_unlock(6);
  thread_unlock(8);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_wait(3, 3);
  thread_yield();
  thread_wait(2, 4);
  thread_unlock(11);
  thread_signal(9, 8);
  thread_yield();
  thread_unlock(0);
  thread_signal(11, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(11, 1);
  thread_yield();
}

void xyz3(void* args) {
  thread_broadcast(0, 6);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(2, 2);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_yield();
  thread_broadcast(5, 2);
  thread_yield();
  thread_lock(4);
  thread_yield();
  thread_unlock(5);
  thread_yield();
  thread_signal(5, 1);
  thread_signal(1, 1);
  thread_signal(6, 3);
  thread_wait(0, 3);
  thread_lock(4);
  thread_yield();
  thread_signal(5, 5);
  cout << "12448998" << endl;
  thread_yield();
  thread_broadcast(3, 5);
  thread_broadcast(1, 5);
  thread_unlock(1);
}

void xyz4(void* args) {
  thread_broadcast(4, 4);
  thread_yield();
  thread_signal(8, 6);
  cout << "88254316" << endl;
  cout << "72257582" << endl;
  thread_wait(8, 2);
  thread_wait(2, 1);
  cout << "76845617" << endl;
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_signal(8, 4);
  thread_yield();
  thread_broadcast(6, 5);
  cout << "8499495" << endl;
  thread_yield();
  thread_unlock(0);
  thread_unlock(2);
  cout << "60318050" << endl;
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(0, 4);
  thread_signal(8, 8);
  cout << "115194858" << endl;
  thread_yield();
  thread_broadcast(3, 2);
  thread_unlock(4);
  thread_wait(6, 0);
  thread_yield();
  thread_yield();
  thread_unlock(3);
  thread_lock(5);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_broadcast(4, 3);
  thread_yield();
  thread_broadcast(7, 6);
  thread_wait(6, 5);
  thread_wait(0, 0);
  thread_signal(6, 0);
  thread_unlock(4);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(0, 0);
  thread_unlock(0);
  thread_signal(8, 5);
  thread_signal(6, 1);
}

void xyz5(void* args) {
  thread_unlock(7);
  thread_signal(3, 0);
  thread_broadcast(13, 9);
  thread_signal(7, 4);
  cout << "914020" << endl;
  thread_unlock(10);
  thread_yield();
  cout << "966688" << endl;
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_broadcast(18, 5);
  thread_yield();
  thread_yield();
  thread_broadcast(16, 17);
  thread_yield();
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  cout << "710837" << endl;
  thread_yield();
  thread_lock(10);
  cout << "1139500" << endl;
  thread_yield();
  cout << "311892" << endl;
  cout << "693772" << endl;
  thread_broadcast(7, 6);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(10);
  thread_yield();
  thread_yield();
  thread_lock(14);
  thread_yield();
  thread_wait(3, 16);
  cout << "174280" << endl;
  thread_lock(2);
  cout << "912539" << endl;
  thread_yield();
  thread_unlock(7);
  thread_lock(0);
  thread_broadcast(10, 14);
  cout << "616360" << endl;
  thread_lock(5);
  thread_yield();
  thread_broadcast(7, 8);
  thread_yield();
  cout << "1138399" << endl;
  thread_broadcast(0, 0);
  thread_yield();
  thread_broadcast(6, 5);
  thread_signal(0, 2);
  thread_unlock(7);
  thread_signal(2, 13);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(18, 7);
  thread_signal(6, 1);
  thread_unlock(18);
  thread_yield();
  thread_signal(11, 4);
  thread_lock(15);
  thread_lock(0);
  thread_yield();
  thread_lock(6);
  thread_yield();
  cout << "410670" << endl;
  thread_yield();
  cout << "46458" << endl;
  cout << "293389" << endl;
  thread_signal(5, 8);
  thread_yield();
  thread_broadcast(4, 0);
  thread_yield();
  thread_signal(13, 5);
  thread_broadcast(14, 11);
  thread_signal(13, 10);
  thread_broadcast(5, 2);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_signal(18, 10);
  thread_unlock(0);
  thread_yield();
  thread_yield();
  thread_broadcast(12, 8);
  thread_wait(2, 10);
  thread_signal(15, 7);
  thread_signal(10, 16);
  thread_broadcast(6, 0);
  thread_yield();
  thread_unlock(11);
  thread_yield();
  thread_signal(4, 11);
  thread_unlock(1);
  thread_yield();
  thread_unlock(11);
  thread_unlock(1);
  thread_yield();
  thread_lock(9);
  thread_yield();
  thread_yield();
  thread_lock(8);
  thread_unlock(3);
  thread_yield();
  thread_yield();
  thread_broadcast(9, 8);
  thread_yield();
  cout << "536633" << endl;
  thread_yield();
  thread_yield();
  cout << "775745" << endl;
  thread_yield();
  thread_signal(17, 10);
  thread_broadcast(18, 5);
  thread_signal(9, 0);
  thread_yield();
  thread_broadcast(7, 6);
  thread_wait(11, 18);
  thread_yield();
}

void xyz6(void* args) {
  cout << "573343" << endl;
  thread_yield();
  thread_unlock(3);
  thread_lock(2);
  thread_signal(1, 1);
  thread_lock(2);
  thread_signal(1, 2);
  thread_signal(2, 2);
  thread_lock(3);
  thread_wait(2, 3);
  thread_lock(0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_broadcast(2, 1);
  thread_wait(3, 1);
  cout << "429674" << endl;
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_yield();
  cout << "365736" << endl;
  thread_unlock(2);
  thread_wait(2, 0);
  thread_yield();
  cout << "1113026" << endl;
  thread_unlock(2);
  cout << "936063" << endl;
  thread_wait(3, 2);
  thread_yield();
  thread_unlock(0);
  thread_broadcast(0, 2);
  thread_broadcast(1, 3);
  thread_wait(1, 1);
  thread_yield();
  thread_lock(2);
  thread_yield();
  thread_lock(2);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "1037617" << endl;
  cout << "897276" << endl;
  thread_yield();
  thread_lock(1);
}

void xyz7(void* args) {
  thread_unlock(7);
  thread_yield();
  thread_lock(2);
  thread_yield();
  cout << "1499266" << endl;
  thread_wait(10, 1);
  cout << "2958288" << endl;
  cout << "476632" << endl;
  thread_yield();
  thread_yield();
  cout << "1507218" << endl;
  thread_lock(10);
  thread_lock(3);
  thread_yield();
  cout << "3126339" << endl;
  thread_lock(5);
  thread_lock(4);
  thread_wait(0, 6);
  thread_broadcast(8, 10);
  thread_signal(7, 1);
  thread_yield();
  thread_wait(12, 8);
  thread_yield();
  thread_lock(5);
  thread_broadcast(7, 6);
  thread_signal(0, 0);
  thread_broadcast(8, 2);
  thread_signal(0, 7);
  thread_yield();
  thread_yield();
  cout << "2096972" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_wait(5, 2);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "114003" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(12);
  thread_yield();
  thread_signal(11, 6);
  thread_unlock(11);
  thread_yield();
  thread_broadcast(9, 1);
  thread_yield();
  cout << "1303837" << endl;
  thread_yield();
  thread_signal(7, 6);
  thread_yield();
  thread_yield();
  thread_wait(4, 10);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(8);
  thread_lock(6);
  thread_signal(3, 12);
  thread_wait(9, 1);
  thread_wait(9, 5);
  thread_signal(6, 12);
  thread_broadcast(9, 9);
  thread_yield();
  thread_yield();
  thread_unlock(11);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "2734153" << endl;
  thread_yield();
  thread_unlock(4);
  thread_broadcast(13, 12);
  thread_broadcast(6, 2);
  thread_unlock(12);
  thread_broadcast(7, 8);
  cout << "662797" << endl;
  thread_signal(8, 11);
  cout << "1416665" << endl;
  thread_lock(13);
  thread_unlock(11);
  thread_yield();
  thread_yield();
  thread_signal(12, 1);
  thread_signal(9, 4);
  thread_yield();
  thread_yield();
  thread_lock(8);
}

void xyz8(void* args) {
  thread_lock(0);
  thread_broadcast(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(0, 2);
  thread_yield();
  thread_wait(1, 1);
  cout << "20304" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(2, 0);
}

void xyz9(void* args) {
  thread_lock(0);
  thread_signal(1, 1);
  thread_signal(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(0, 1);
  thread_unlock(0);
  thread_signal(1, 1);
  cout << "1852819" << endl;
  thread_unlock(0);
  cout << "505792" << endl;
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_lock(0);
  thread_lock(1);
  thread_unlock(0);
  thread_broadcast(1, 0);
  thread_yield();
  thread_unlock(0);
  thread_signal(0, 0);
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_broadcast(0, 1);
  thread_yield();
  thread_lock(1);
  thread_broadcast(0, 0);
  thread_unlock(1);
  thread_broadcast(1, 1);
  thread_lock(1);
  thread_wait(1, 1);
  thread_unlock(0);
  thread_signal(1, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_signal(0, 0);
  thread_signal(0, 1);
  thread_wait(1, 0);
  thread_yield();
  thread_unlock(1);
  thread_signal(1, 1);
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_wait(1, 0);
  thread_yield();
  thread_broadcast(0, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "172662" << endl;
  thread_lock(1);
  thread_yield();
  thread_yield();
  thread_broadcast(0, 0);
  thread_yield();
  thread_wait(1, 0);
  thread_yield();
  thread_unlock(0);
  thread_yield();
  cout << "1535560" << endl;
  thread_yield();
  thread_signal(1, 0);
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
}

void xyz10(void* args) {
  thread_lock(2);
  thread_signal(1, 2);
  thread_broadcast(4, 3);
  thread_wait(2, 5);
  thread_broadcast(3, 0);
  thread_unlock(1);
  thread_unlock(2);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(4, 0);
  thread_signal(0, 4);
  thread_unlock(0);
  thread_signal(1, 2);
  thread_yield();
  thread_signal(1, 5);
  thread_yield();
  cout << "1889" << endl;
  cout << "138152" << endl;
  thread_lock(0);
  thread_yield();
  thread_unlock(2);
  thread_yield();
  thread_yield();
  thread_broadcast(2, 5);
  thread_yield();
  thread_broadcast(1, 4);
  cout << "231570" << endl;
  thread_signal(1, 3);
  thread_broadcast(2, 0);
  thread_unlock(1);
  thread_yield();
  thread_yield();
  thread_unlock(4);
  thread_signal(2, 2);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(4, 5);
  thread_yield();
  thread_yield();
  thread_signal(2, 3);
  thread_yield();
  thread_signal(0, 0);
  thread_broadcast(0, 5);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(4);
  thread_signal(0, 0);
  cout << "157031" << endl;
  thread_yield();
  cout << "39027" << endl;
  thread_lock(3);
  thread_yield();
  thread_broadcast(0, 2);
  thread_wait(3, 1);
  cout << "195982" << endl;
  thread_yield();
}

void maker(void *args) {
  thread_broadcast(1, 0);
  thread_wait(1, 0);
  thread_signal(1, 0);
  thread_broadcast(0, 0);
  thread_unlock(1);
  thread_signal(0, 0);
  thread_signal(0, 0);
  thread_yield();
  thread_broadcast(0, 1);
  thread_create((thread_startfunc_t) xyz1, (void *) 100);
  thread_create((thread_startfunc_t) xyz2, (void *) 100);
  thread_wait(0, 1);
  thread_broadcast(0, 0);
  thread_create((thread_startfunc_t) xyz3, (void *) 100);
  thread_signal(0, 1);
  thread_wait(0, 1);
  thread_broadcast(0, 0);
  thread_unlock(0);
  thread_unlock(0);
  thread_lock(0);
  thread_broadcast(1, 0);
  thread_wait(0, 0);
  thread_create((thread_startfunc_t) xyz4, (void *) 100);
  thread_create((thread_startfunc_t) xyz5, (void *) 100);
  thread_wait(0, 0);
  thread_create((thread_startfunc_t) xyz6, (void *) 100);
  thread_lock(1);
  thread_create((thread_startfunc_t) xyz7, (void *) 100);
  thread_lock(0);
  thread_signal(0, 1);
  thread_create((thread_startfunc_t) xyz8, (void *) 100);
  thread_create((thread_startfunc_t) xyz9, (void *) 100);
  thread_wait(0, 1);
  thread_broadcast(1, 1);
  thread_broadcast(1, 0);
  thread_yield();
  thread_create((thread_startfunc_t) xyz10, (void *) 100);
  thread_yield();
  thread_yield();
  thread_wait(0, 1);
  thread_wait(0, 0);
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_wait(1, 1);
  thread_unlock(0);
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(1, 1);
  thread_yield();
  thread_unlock(1);
  thread_signal(0, 1);
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_broadcast(1, 0);
  thread_lock(1);
  thread_broadcast(1, 0);
  thread_lock(0);
  thread_yield();
  thread_signal(1, 0);
  thread_lock(1);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(0, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(0, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_broadcast(0, 0);
  thread_unlock(1);
  thread_broadcast(0, 1);
  thread_wait(1, 1);
  thread_unlock(1);
  thread_signal(0, 0);
  thread_broadcast(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 1);
  thread_yield();
}

int main(int argc, char *argv[]) {
  thread_libinit((thread_startfunc_t)maker, &argc);
}
