#include <stdlib.h>
#include <iostream>
#include "thread.h"
#include <assert.h>
#include <vector>
#include <string.h>
#include <fstream>
using namespace std;

void xyz1(void* args);
void xyz2(void* args);
void xyz3(void* args);
void xyz4(void* args);
void xyz5(void* args);
void xyz6(void* args);
void xyz7(void* args) ;
void xyz8(void* args);
void xyz9(void* args);
void xyz10(void* args);
void maker(void *args);
void xyz1(void* args) {
  thread_unlock(1);
  thread_unlock(0);
  thread_unlock(0);
  cout << "94198601" << endl;
  thread_lock(0);
  thread_unlock(0);
  thread_broadcast(0, 0);
  thread_yield();
  cout << "60773661" << endl;
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_lock(1);
  thread_wait(1, 0);
  thread_wait(1, 0);
  thread_yield();
  thread_broadcast(0, 0);
  thread_unlock(0);
  thread_lock(1);
  thread_broadcast(1, 1);
  thread_yield();
  thread_broadcast(1, 0);
  thread_unlock(0);
  thread_lock(0);
  thread_yield();
  thread_broadcast(0, 1);
  thread_lock(0);
  thread_signal(0, 0);
  cout << "59714606" << endl;
  thread_unlock(0);
  thread_signal(1, 0);
  thread_yield();
  thread_wait(0, 1);
  thread_broadcast(0, 1);
  thread_wait(0, 1);
  thread_unlock(0);
  thread_wait(0, 1);
  thread_signal(1, 1);
  thread_wait(1, 1);
  thread_unlock(0);
  cout << "52430756" << endl;
  thread_lock(1);
  thread_unlock(0);
  cout << "19831035" << endl;
  thread_signal(1, 0);
  thread_yield();
  thread_wait(0, 0);
  thread_broadcast(1, 1);
  thread_signal(1, 0);
  thread_signal(1, 0);
  thread_broadcast(0, 0);
  cout << "111677913" << endl;
  thread_broadcast(1, 0);
  cout << "67313837" << endl;
  thread_lock(1);
  cout << "23287846" << endl;
  thread_lock(1);
  thread_wait(1, 0);
  thread_lock(0);
  cout << "66963880" << endl;
  thread_wait(0, 1);
  thread_unlock(1);
  thread_broadcast(0, 1);
  cout << "53048736" << endl;
  thread_signal(1, 1);
  cout << "117931850" << endl;
  thread_signal(1, 1);
  thread_lock(1);
  thread_yield();
  cout << "110939217" << endl;
  thread_unlock(1);
  thread_lock(1);
  thread_wait(1, 1);
  thread_unlock(0);
  thread_lock(0);
  cout << "111906812" << endl;
  thread_signal(1, 1);
  cout << "102073038" << endl;
  thread_signal(0, 0);
  cout << "53007607" << endl;
  thread_broadcast(1, 0);
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_signal(1, 1);
  thread_signal(1, 0);
  thread_yield();
  thread_yield();
  thread_signal(0, 1);
  thread_broadcast(1, 1);
  thread_yield();
  thread_wait(1, 0);
  thread_signal(0, 1);
  thread_broadcast(0, 0);
  thread_broadcast(0, 0);
  thread_broadcast(0, 1);
  thread_signal(0, 1);
  thread_signal(0, 1);
  thread_yield();
  thread_broadcast(0, 0);
  thread_lock(0);
  thread_signal(0, 1);
  thread_wait(1, 1);
  thread_yield();
  thread_unlock(1);
  thread_signal(0, 1);
  thread_unlock(0);
  thread_lock(0);
  thread_broadcast(1, 0);
  thread_lock(1);
  thread_broadcast(1, 1);
  thread_lock(1);
  thread_yield();
  thread_wait(0, 0);
  thread_yield();
  thread_broadcast(1, 0);
  thread_unlock(0);
  cout << "116075499" << endl;
  thread_signal(0, 1);
  cout << "81299326" << endl;
  cout << "111163348" << endl;
  thread_wait(1, 1);
  thread_wait(1, 0);
  cout << "91436032" << endl;
  thread_lock(1);
  thread_signal(0, 1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(1, 0);
  thread_yield();
  thread_lock(1);
  thread_unlock(0);
  thread_broadcast(1, 1);
  thread_wait(0, 0);
  thread_signal(1, 1);
  thread_unlock(1);
  thread_signal(0, 1);
  cout << "98206068" << endl;
  thread_wait(0, 0);
  thread_broadcast(1, 0);
  cout << "5063963" << endl;
  cout << "87412243" << endl;
  thread_lock(1);
  thread_wait(0, 1);
  thread_signal(1, 1);
  thread_lock(1);
  cout << "66535722" << endl;
  thread_broadcast(0, 1);
  thread_wait(0, 1);
  thread_signal(1, 1);
  thread_broadcast(1, 1);
  thread_yield();
}

void xyz2(void* args) {
  cout << "69007633" << endl;
  thread_broadcast(12, 11);
  thread_unlock(6);
  thread_yield();
  thread_yield();
  thread_signal(1, 6);
  thread_wait(7, 3);
  thread_yield();
  thread_wait(12, 3);
  thread_signal(12, 9);
  thread_yield();
  thread_wait(6, 11);
  thread_yield();
  thread_broadcast(5, 2);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(4, 3);
  thread_yield();
  thread_lock(6);
  thread_wait(9, 5);
  thread_broadcast(3, 2);
  thread_broadcast(8, 6);
  thread_signal(2, 12);
  thread_yield();
  thread_yield();
  thread_broadcast(0, 6);
  thread_unlock(8);
  thread_broadcast(7, 3);
  thread_yield();
  thread_signal(2, 0);
  thread_yield();
  thread_unlock(4);
  thread_broadcast(3, 10);
  thread_unlock(4);
  thread_signal(12, 10);
  thread_broadcast(7, 11);
  thread_yield();
  thread_broadcast(11, 2);
  thread_broadcast(11, 5);
  thread_lock(7);
  thread_unlock(7);
  thread_yield();
  thread_broadcast(5, 12);
  cout << "91815595" << endl;
  thread_lock(5);
  thread_wait(1, 9);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_unlock(5);
  thread_yield();
  thread_unlock(10);
  cout << "114734432" << endl;
  thread_signal(12, 7);
  thread_yield();
  thread_wait(3, 2);
  thread_broadcast(3, 1);
  cout << "1585380" << endl;
  thread_signal(0, 1);
  thread_lock(3);
  thread_yield();
}

void xyz3(void* args) {
  thread_yield();
  cout << "4002604" << endl;
  thread_signal(5, 5);
  thread_yield();
  thread_lock(3);
  thread_signal(2, 6);
  thread_lock(3);
  thread_yield();
  thread_signal(0, 2);
  cout << "6817319" << endl;
  cout << "1084782" << endl;
  thread_signal(1, 4);
  cout << "11760927" << endl;
  cout << "30171" << endl;
  thread_signal(1, 2);
  thread_wait(4, 4);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(3, 0);
  thread_wait(6, 4);
  thread_broadcast(0, 6);
  thread_broadcast(6, 6);
  thread_yield();
  thread_signal(5, 6);
}

void xyz4(void* args) {
  thread_yield();
  thread_yield();
  thread_wait(1, 6);
  thread_unlock(0);
  thread_unlock(6);
  thread_yield();
  thread_broadcast(2, 4);
  thread_lock(2);
  thread_signal(5, 5);
  thread_yield();
  thread_wait(6, 1);
  thread_broadcast(5, 7);
  thread_yield();
  thread_wait(2, 0);
  thread_yield();
  thread_signal(1, 6);
  thread_broadcast(2, 3);
  thread_wait(0, 7);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(6);
  thread_yield();
  thread_wait(4, 8);
  thread_yield();
  thread_unlock(7);
  thread_yield();
  thread_wait(2, 8);
  thread_unlock(1);
  thread_signal(4, 6);
  cout << "85285502" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(8, 8);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_unlock(4);
  thread_yield();
  thread_wait(8, 2);
  thread_yield();
  thread_yield();
  thread_signal(3, 2);
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_yield();
}

void xyz5(void* args) {
  thread_lock(11);
  thread_broadcast(15, 3);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(2);
  thread_signal(12, 12);
  thread_signal(1, 17);
  thread_signal(3, 16);
  thread_unlock(6);
  thread_wait(10, 15);
  thread_lock(8);
  thread_yield();
  thread_signal(16, 14);
  thread_signal(0, 9);
  cout << "69047" << endl;
  thread_broadcast(7, 7);
  thread_yield();
  thread_wait(14, 11);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_yield();
  thread_unlock(16);
  thread_yield();
  thread_unlock(12);
  cout << "554756" << endl;
  thread_signal(12, 17);
  thread_yield();
  thread_wait(11, 12);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(12, 3);
  thread_wait(8, 11);
  thread_signal(15, 17);
  thread_wait(0, 18);
  thread_yield();
  thread_broadcast(1, 3);
  thread_signal(6, 14);
  thread_wait(18, 12);
  thread_yield();
  thread_yield();
  thread_wait(1, 8);
  thread_broadcast(7, 5);
  thread_unlock(10);
  thread_unlock(13);
  thread_unlock(15);
  thread_unlock(16);
  thread_yield();
  thread_yield();
  thread_broadcast(15, 11);
  thread_unlock(7);
  thread_signal(1, 10);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(11);
  thread_signal(14, 15);
  thread_yield();
  thread_wait(5, 15);
  cout << "1034837" << endl;
  thread_yield();
  thread_wait(3, 2);
  thread_yield();
  thread_yield();
  thread_signal(10, 8);
  thread_yield();
  thread_wait(15, 14);
  cout << "922615" << endl;
  thread_signal(5, 4);
  thread_yield();
  cout << "835048" << endl;
  thread_signal(6, 8);
  thread_yield();
  thread_wait(5, 10);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(4);
  cout << "165314" << endl;
  thread_broadcast(0, 0);
  cout << "950228" << endl;
  thread_yield();
  thread_lock(2);
  thread_yield();
  cout << "1181502" << endl;
  thread_yield();
  thread_broadcast(15, 14);
  cout << "80762" << endl;
  thread_yield();
  thread_yield();
  cout << "1042029" << endl;
  thread_yield();
  thread_unlock(5);
  thread_wait(15, 8);
  thread_lock(3);
  thread_yield();
  thread_wait(15, 5);
  thread_wait(14, 10);
  thread_yield();
  cout << "176188" << endl;
  thread_unlock(5);
  thread_broadcast(5, 18);
  thread_yield();
  cout << "235518" << endl;
  thread_wait(16, 3);
  cout << "1033846" << endl;
  thread_lock(3);
  thread_unlock(1);
  cout << "217514" << endl;
  thread_yield();
  thread_signal(5, 2);
  thread_lock(17);
  thread_unlock(14);
  thread_yield();
  thread_yield();
  thread_signal(4, 1);
  thread_signal(12, 6);
  thread_broadcast(0, 0);
  thread_broadcast(1, 9);
  cout << "751738" << endl;
  thread_broadcast(4, 8);
  thread_unlock(12);
  thread_wait(10, 14);
  thread_broadcast(17, 8);
  thread_yield();
}

void xyz6(void* args) {
  thread_yield();
  thread_broadcast(0, 1);
  thread_lock(0);
  thread_signal(1, 3);
  thread_wait(2, 0);
  cout << "143727" << endl;
  cout << "18947" << endl;
  thread_yield();
  thread_yield();
  thread_broadcast(3, 2);
  thread_yield();
  thread_signal(3, 2);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(3, 3);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(3);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(0);
  thread_lock(0);
  thread_broadcast(2, 0);
  thread_yield();
  thread_signal(1, 0);
  thread_yield();
  thread_wait(3, 1);
  thread_broadcast(1, 2);
  thread_yield();
  cout << "1085246" << endl;
  thread_yield();
  thread_yield();
  cout << "1073766" << endl;
  thread_yield();
  thread_yield();
  cout << "579729" << endl;
  thread_lock(2);
  thread_yield();
  cout << "1111836" << endl;
}

void xyz7(void* args) {
  cout << "1542082" << endl;
  thread_yield();
  thread_yield();
  thread_broadcast(11, 4);
  thread_yield();
  cout << "2611742" << endl;
  thread_lock(4);
  thread_yield();
  thread_yield();
  cout << "708772" << endl;
  thread_lock(6);
  thread_lock(8);
  thread_lock(7);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(7, 11);
  thread_yield();
  thread_yield();
  thread_unlock(5);
  thread_wait(0, 11);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_broadcast(9, 7);
  thread_broadcast(2, 3);
  thread_signal(11, 4);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "27350" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(0, 9);
  cout << "92848" << endl;
  thread_unlock(5);
  thread_yield();
  thread_yield();
  cout << "2432827" << endl;
  thread_yield();
  thread_yield();
  thread_unlock(9);
  thread_broadcast(9, 8);
  thread_signal(9, 3);
  thread_wait(1, 0);
  thread_lock(6);
  cout << "2476311" << endl;
  thread_yield();
  cout << "1595272" << endl;
  thread_yield();
  thread_lock(9);
  thread_yield();
  thread_yield();
  thread_lock(10);
  thread_wait(6, 6);
  thread_yield();
  thread_unlock(8);
  thread_yield();
  thread_broadcast(7, 4);
  thread_yield();
  thread_signal(6, 2);
  thread_yield();
  thread_signal(3, 10);
  cout << "2288214" << endl;
  thread_broadcast(13, 5);
  thread_unlock(6);
  cout << "683608" << endl;
  thread_yield();
  thread_lock(8);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_unlock(2);
  thread_broadcast(0, 11);
  thread_lock(13);
  thread_yield();
  thread_broadcast(1, 8);
  thread_broadcast(3, 12);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(3);
  thread_yield();
  thread_unlock(8);
  thread_lock(12);
  cout << "2059096" << endl;
  thread_signal(3, 13);
  thread_unlock(9);
}

void xyz8(void* args) {
  thread_yield();
  thread_broadcast(1, 2);
  thread_yield();
  thread_wait(2, 2);
  thread_wait(1, 1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(1, 0);
  thread_yield();
  cout << "16173" << endl;
  thread_yield();
  thread_lock(1);
  thread_wait(2, 1);
  thread_wait(0, 0);
  thread_yield();
  cout << "14089" << endl;
  thread_signal(2, 0);
  cout << "3978" << endl;
  thread_lock(2);
  thread_signal(2, 2);
  thread_lock(2);
  thread_unlock(2);
}

void xyz9(void* args) {
  thread_unlock(0);
  thread_unlock(1);
  thread_yield();
  cout << "1294493" << endl;
  thread_lock(1);
  thread_wait(0, 1);
  thread_yield();
  thread_unlock(0);
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_unlock(1);
  thread_broadcast(0, 1);
  thread_broadcast(1, 0);
  thread_yield();
  thread_wait(1, 1);
  thread_unlock(0);
  cout << "1201094" << endl;
  thread_yield();
  thread_lock(1);
  thread_wait(1, 0);
  cout << "813441" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 0);
  thread_yield();
  thread_lock(0);
  thread_broadcast(0, 1);
  thread_yield();
  thread_wait(1, 1);
  thread_unlock(1);
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_wait(0, 0);
  thread_broadcast(1, 0);
  thread_broadcast(1, 1);
  cout << "1326149" << endl;
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_wait(0, 1);
  cout << "240146" << endl;
  thread_lock(0);
  thread_lock(1);
  thread_unlock(1);
  thread_yield();
  thread_unlock(1);
  thread_lock(1);
  thread_unlock(0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_broadcast(0, 0);
  thread_broadcast(0, 0);
  thread_unlock(0);
  cout << "2182369" << endl;
  thread_unlock(1);
  cout << "1498777" << endl;
  thread_lock(1);
  cout << "1449575" << endl;
  thread_wait(1, 0);
  thread_unlock(1);
  thread_signal(0, 0);
  thread_yield();
  cout << "110483" << endl;
  thread_yield();
  thread_signal(1, 1);
  thread_broadcast(0, 0);
  thread_broadcast(1, 1);
  thread_wait(0, 0);
  thread_yield();
  thread_signal(1, 1);
  thread_unlock(0);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_wait(1, 0);
  thread_unlock(1);
  cout << "2106867" << endl;
  thread_unlock(1);
  thread_wait(1, 0);
}

void xyz10(void* args) {
  thread_signal(4, 2);
  thread_signal(0, 2);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(2);
  thread_yield();
  thread_unlock(0);
  thread_signal(0, 0);
  thread_lock(1);
  thread_wait(1, 0);
  thread_wait(1, 1);
  thread_yield();
  thread_yield();
  thread_wait(0, 4);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(3);
  thread_signal(3, 5);
  cout << "212834" << endl;
  thread_yield();
  thread_signal(1, 5);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(3);
  cout << "141574" << endl;
  thread_yield();
  thread_signal(0, 3);
  thread_wait(4, 3);
  thread_unlock(2);
  thread_yield();
  thread_broadcast(1, 4);
  thread_yield();
  thread_yield();
  cout << "150504" << endl;
  thread_yield();
  thread_lock(3);
  thread_unlock(1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_wait(0, 4);
  thread_broadcast(1, 5);
  thread_wait(2, 0);
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_lock(2);
  thread_unlock(4);
  thread_yield();
  thread_wait(3, 5);
  cout << "6036" << endl;
  thread_yield();
  thread_broadcast(2, 1);
  thread_signal(4, 4);
  thread_yield();
  thread_yield();
  thread_wait(1, 3);
  thread_signal(1, 3);
  thread_yield();
}

void maker(void *args) {
  thread_yield();
  thread_yield();
  thread_unlock(0);
  thread_signal(1, 1);
  thread_unlock(0);
  thread_create((thread_startfunc_t) xyz1, (void *) 100);
  thread_unlock(1);
  thread_unlock(1);
  thread_signal(0, 0);
  thread_create((thread_startfunc_t) xyz2, (void *) 100);
  thread_wait(0, 1);
  thread_create((thread_startfunc_t) xyz3, (void *) 100);
  thread_create((thread_startfunc_t) xyz4, (void *) 100);
  thread_create((thread_startfunc_t) xyz5, (void *) 100);
  thread_wait(0, 1);
  thread_wait(0, 0);
  thread_create((thread_startfunc_t) xyz6, (void *) 100);
  thread_yield();
  thread_create((thread_startfunc_t) xyz7, (void *) 100);
  thread_wait(1, 1);
  thread_wait(0, 0);
  thread_wait(0, 1);
  thread_create((thread_startfunc_t) xyz8, (void *) 100);
  thread_lock(0);
  thread_create((thread_startfunc_t) xyz9, (void *) 100);
  thread_yield();
  thread_broadcast(1, 1);
  thread_yield();
  thread_signal(1, 0);
  thread_signal(1, 0);
  thread_broadcast(0, 1);
  thread_wait(1, 0);
  thread_unlock(1);
  thread_lock(0);
  thread_create((thread_startfunc_t) xyz10, (void *) 100);
  thread_signal(0, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(1, 1);
  thread_yield();
  thread_broadcast(0, 0);
  thread_unlock(1);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(0, 1);
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_signal(0, 1);
  thread_yield();
  thread_broadcast(0, 0);
  thread_lock(0);
  thread_broadcast(0, 1);
  thread_yield();
  thread_lock(1);
  thread_signal(0, 1);
  thread_wait(0, 0);
  thread_lock(1);
  thread_broadcast(1, 1);
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_lock(0);
  thread_yield();
  thread_wait(0, 1);
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 1);
  thread_signal(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 1);
  thread_lock(0);
  thread_yield();
  thread_signal(0, 0);
  thread_lock(0);
  thread_unlock(1);
  thread_wait(0, 1);
}

int main(int argc, char *argv[]) {
  thread_libinit((thread_startfunc_t)maker, &argc);
}
