#include <stdlib.h>
#include <iostream>
#include "thread.h"
#include <assert.h>
#include <vector>
#include <string.h>
#include <fstream>
using namespace std;

void xyz1(void* args);
void xyz2(void* args);
void xyz3(void* args);
void xyz4(void* args);
void xyz5(void* args);
void xyz6(void* args);
void xyz7(void* args) ;
void xyz8(void* args);
void xyz9(void* args);
void xyz10(void* args);
void maker(void *args);
void xyz1(void* args) {
  thread_unlock(1);
  thread_wait(0, 0);
  cout << "5927121" << endl;
  thread_unlock(1);
  thread_broadcast(0, 0);
  cout << "13353098" << endl;
  thread_signal(1, 0);
  thread_unlock(1);
  thread_unlock(0);
  thread_yield();
  thread_wait(1, 1);
  thread_broadcast(0, 0);
  thread_yield();
  thread_lock(1);
  thread_lock(1);
  thread_signal(1, 0);
  cout << "48892059" << endl;
  thread_signal(0, 0);
  cout << "104640349" << endl;
  thread_signal(1, 1);
  thread_unlock(1);
  thread_broadcast(0, 1);
  thread_lock(0);
  thread_signal(1, 0);
  thread_lock(1);
  cout << "63336139" << endl;
  thread_broadcast(0, 1);
  thread_unlock(0);
  cout << "7451624" << endl;
  thread_lock(1);
  thread_lock(0);
  thread_signal(1, 0);
  thread_signal(0, 1);
  thread_wait(0, 1);
  cout << "8002017" << endl;
  cout << "48128056" << endl;
  thread_wait(1, 1);
  thread_signal(0, 1);
  thread_broadcast(1, 1);
  thread_unlock(1);
  thread_unlock(1);
  thread_yield();
  thread_broadcast(1, 0);
  thread_signal(1, 1);
  thread_lock(1);
  thread_lock(1);
  thread_lock(0);
  thread_broadcast(1, 1);
  thread_signal(1, 1);
  thread_lock(0);
  thread_yield();
  thread_broadcast(1, 0);
  thread_unlock(0);
  thread_signal(0, 1);
  thread_broadcast(0, 0);
  cout << "59899834" << endl;
  thread_lock(0);
  cout << "595140" << endl;
  cout << "122123510" << endl;
  thread_signal(0, 0);
  thread_wait(0, 1);
  thread_lock(1);
  thread_lock(0);
  cout << "75639642" << endl;
  thread_unlock(0);
  thread_lock(1);
  thread_unlock(0);
  thread_broadcast(0, 0);
  thread_signal(1, 0);
  cout << "58482048" << endl;
  thread_broadcast(1, 1);
  thread_unlock(0);
  thread_wait(0, 0);
  thread_signal(1, 1);
  thread_signal(1, 0);
  thread_broadcast(1, 1);
  cout << "120025859" << endl;
  thread_broadcast(0, 0);
  thread_unlock(0);
  cout << "73408079" << endl;
  thread_wait(1, 0);
  thread_signal(0, 0);
  thread_wait(1, 1);
  thread_unlock(0);
  cout << "90679673" << endl;
  thread_broadcast(0, 1);
  thread_yield();
  thread_broadcast(0, 0);
  thread_lock(0);
  thread_broadcast(0, 0);
  thread_unlock(0);
  thread_broadcast(1, 1);
  cout << "10383232" << endl;
  thread_signal(1, 1);
  thread_broadcast(0, 1);
  cout << "115458289" << endl;
  thread_unlock(1);
  thread_wait(1, 0);
  thread_unlock(0);
  thread_lock(1);
  cout << "30753036" << endl;
  cout << "38230879" << endl;
  thread_broadcast(0, 0);
  thread_yield();
  thread_wait(1, 1);
  cout << "94617679" << endl;
  cout << "32108379" << endl;
  cout << "105494926" << endl;
  thread_lock(1);
  thread_wait(0, 1);
  thread_lock(1);
  thread_broadcast(0, 0);
  thread_unlock(1);
  thread_wait(1, 0);
  cout << "39164462" << endl;
  cout << "53758399" << endl;
  thread_lock(1);
  thread_signal(1, 0);
  thread_wait(1, 1);
  thread_unlock(1);
  thread_wait(1, 0);
  thread_wait(0, 0);
  thread_signal(1, 0);
  thread_unlock(0);
  thread_wait(0, 0);
  thread_wait(0, 1);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(0, 0);
  thread_wait(0, 0);
  thread_unlock(0);
  thread_unlock(1);
  thread_signal(1, 0);
  thread_lock(1);
  cout << "45282929" << endl;
  cout << "74665849" << endl;
  thread_lock(1);
  thread_broadcast(0, 0);
  cout << "17793739" << endl;
  thread_wait(0, 0);
  thread_signal(0, 1);
  thread_wait(0, 1);
  thread_unlock(1);
  thread_unlock(1);
  thread_signal(0, 0);
  thread_signal(1, 1);
  thread_wait(0, 0);
  thread_yield();
  thread_signal(0, 1);
  thread_wait(0, 1);
  thread_unlock(0);
  thread_unlock(0);
}

void xyz2(void* args) {
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "32605884" << endl;
  thread_broadcast(6, 7);
  thread_yield();
  thread_lock(7);
  thread_yield();
  thread_lock(6);
  thread_wait(1, 4);
  thread_yield();
  thread_yield();
  thread_unlock(11);
  thread_wait(9, 3);
  thread_unlock(12);
  thread_unlock(0);
  thread_yield();
  thread_unlock(5);
  thread_yield();
  thread_yield();
  thread_unlock(8);
  thread_yield();
  thread_signal(10, 5);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "35628033" << endl;
  thread_wait(11, 1);
  thread_yield();
  thread_lock(5);
  thread_yield();
  thread_yield();
  thread_unlock(12);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_lock(4);
  thread_yield();
  thread_signal(7, 6);
  thread_yield();
  thread_wait(7, 6);
  thread_yield();
  thread_yield();
  thread_broadcast(9, 3);
  cout << "115220315" << endl;
  cout << "22983316" << endl;
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_signal(1, 2);
  thread_yield();
  thread_unlock(10);
  thread_yield();
  thread_yield();
  thread_wait(10, 5);
  thread_lock(7);
  thread_broadcast(6, 5);
  thread_lock(3);
  thread_yield();
}

void xyz3(void* args) {
  thread_yield();
  thread_broadcast(2, 3);
  thread_lock(4);
  thread_lock(1);
  thread_yield();
  thread_signal(0, 5);
  cout << "11345856" << endl;
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_signal(5, 6);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "9398082" << endl;
  thread_wait(5, 6);
  thread_wait(1, 2);
  thread_unlock(6);
  thread_yield();
  thread_unlock(6);
  thread_wait(1, 3);
  thread_unlock(2);
  thread_yield();
  cout << "10026793" << endl;
  thread_wait(0, 2);
  thread_yield();
  thread_unlock(0);
  cout << "74113" << endl;
}

void xyz4(void* args) {
  thread_lock(0);
  thread_lock(0);
  thread_signal(8, 5);
  thread_yield();
  cout << "32632822" << endl;
  thread_signal(4, 8);
  thread_wait(5, 7);
  thread_unlock(8);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(4, 6);
  thread_signal(5, 0);
  thread_yield();
  thread_broadcast(2, 7);
  thread_yield();
  thread_broadcast(8, 8);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_signal(1, 2);
  thread_lock(8);
  thread_yield();
  thread_yield();
  thread_unlock(5);
  thread_signal(7, 7);
  thread_yield();
  thread_wait(7, 1);
  thread_yield();
  thread_unlock(7);
  thread_wait(7, 6);
  thread_signal(3, 8);
  thread_wait(3, 5);
  thread_signal(8, 8);
  cout << "57070220" << endl;
  thread_unlock(4);
  thread_yield();
  thread_broadcast(3, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(4, 0);
  thread_yield();
  thread_yield();
  thread_signal(4, 2);
  thread_wait(3, 0);
  thread_wait(3, 1);
  thread_yield();
  thread_unlock(7);
  thread_signal(2, 1);
  thread_yield();
}

void xyz5(void* args) {
  thread_yield();
  cout << "540745" << endl;
  thread_yield();
  thread_lock(4);
  cout << "97503" << endl;
  thread_signal(17, 4);
  thread_yield();
  cout << "1048045" << endl;
  thread_broadcast(16, 17);
  thread_yield();
  thread_yield();
  cout << "131146" << endl;
  thread_yield();
  thread_unlock(15);
  thread_unlock(13);
  thread_yield();
  thread_yield();
  thread_signal(0, 7);
  thread_unlock(17);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(12);
  thread_unlock(5);
  thread_yield();
  thread_yield();
  thread_broadcast(10, 11);
  thread_unlock(13);
  thread_broadcast(11, 5);
  thread_signal(16, 16);
  thread_broadcast(17, 11);
  cout << "919598" << endl;
  thread_broadcast(6, 12);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "197568" << endl;
  thread_signal(10, 15);
  thread_lock(7);
  thread_yield();
  thread_lock(7);
  thread_yield();
  cout << "80250" << endl;
  thread_yield();
  thread_yield();
  thread_broadcast(15, 7);
  thread_signal(9, 7);
  thread_yield();
  thread_broadcast(3, 0);
  thread_broadcast(12, 18);
  thread_lock(17);
  thread_signal(0, 16);
  thread_yield();
  thread_yield();
  thread_signal(5, 6);
  thread_lock(9);
  cout << "1095975" << endl;
  thread_wait(15, 17);
  cout << "555733" << endl;
  thread_broadcast(13, 4);
  thread_yield();
  thread_yield();
  thread_wait(9, 0);
  thread_yield();
  thread_wait(6, 15);
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_unlock(1);
  thread_yield();
  thread_yield();
  thread_signal(11, 8);
  thread_broadcast(16, 3);
  thread_lock(14);
  thread_yield();
  thread_signal(12, 2);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "543894" << endl;
  thread_broadcast(4, 9);
  thread_broadcast(18, 16);
  thread_unlock(15);
  thread_broadcast(2, 7);
  thread_unlock(2);
  thread_lock(10);
  thread_unlock(8);
  thread_yield();
  thread_lock(0);
  thread_wait(11, 3);
  thread_yield();
  thread_signal(4, 3);
  thread_yield();
  thread_yield();
  thread_lock(6);
  thread_wait(1, 16);
  cout << "594044" << endl;
  thread_broadcast(0, 17);
  thread_signal(13, 5);
  thread_lock(17);
  thread_signal(15, 6);
  thread_yield();
  thread_signal(17, 6);
  thread_broadcast(8, 15);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(17, 10);
  thread_unlock(9);
  thread_unlock(5);
  thread_unlock(18);
  thread_yield();
  thread_wait(18, 8);
  cout << "864223" << endl;
  cout << "734036" << endl;
  thread_unlock(9);
  thread_broadcast(7, 4);
  thread_yield();
  thread_wait(4, 4);
  thread_broadcast(12, 17);
  thread_yield();
  thread_unlock(9);
  thread_yield();
  cout << "841378" << endl;
}

void xyz6(void* args) {
  cout << "540678" << endl;
  cout << "1053232" << endl;
  thread_yield();
  thread_yield();
  thread_wait(2, 3);
  thread_unlock(0);
  thread_yield();
  thread_broadcast(2, 0);
  thread_broadcast(1, 1);
  thread_signal(0, 2);
  thread_yield();
  thread_wait(3, 0);
  thread_broadcast(2, 0);
  thread_signal(3, 3);
  thread_yield();
  thread_wait(3, 1);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_wait(3, 0);
  thread_yield();
  thread_lock(3);
  thread_yield();
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_signal(2, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(3);
  thread_broadcast(2, 0);
  thread_yield();
  thread_wait(1, 2);
  thread_signal(0, 0);
  thread_yield();
  thread_broadcast(1, 3);
  thread_wait(0, 2);
  thread_broadcast(3, 2);
  thread_lock(3);
  thread_lock(2);
}

void xyz7(void* args) {
  thread_yield();
  thread_unlock(4);
  thread_broadcast(13, 10);
  cout << "1141596" << endl;
  thread_broadcast(10, 13);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(2, 7);
  thread_broadcast(3, 7);
  thread_yield();
  thread_yield();
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_broadcast(7, 11);
  thread_yield();
  thread_wait(12, 0);
  thread_signal(8, 4);
  thread_broadcast(12, 1);
  thread_yield();
  thread_lock(6);
  thread_signal(12, 3);
  thread_yield();
  cout << "1523432" << endl;
  thread_wait(12, 12);
  thread_yield();
  thread_broadcast(5, 12);
  thread_signal(7, 3);
  thread_yield();
  thread_unlock(1);
  thread_signal(9, 8);
  thread_yield();
  cout << "3061800" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(5);
  thread_yield();
  thread_yield();
  thread_lock(9);
  thread_signal(9, 2);
  thread_wait(9, 13);
  thread_wait(9, 12);
  thread_signal(3, 11);
  thread_yield();
  thread_unlock(13);
  thread_yield();
  thread_yield();
  thread_unlock(13);
  cout << "699550" << endl;
  thread_lock(11);
  cout << "2848838" << endl;
  thread_lock(5);
  thread_signal(12, 2);
  thread_wait(1, 11);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(7, 7);
  thread_signal(12, 8);
  cout << "2089372" << endl;
  thread_wait(12, 7);
  thread_yield();
  thread_yield();
  cout << "2970193" << endl;
  thread_signal(5, 9);
  thread_yield();
  thread_wait(3, 6);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_yield();
  thread_wait(9, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(13, 12);
  thread_signal(6, 8);
  thread_broadcast(11, 8);
  thread_yield();
  thread_yield();
  thread_broadcast(5, 7);
  thread_lock(10);
  thread_unlock(11);
  thread_yield();
  cout << "2874828" << endl;
  thread_lock(1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(0, 1);
}

void xyz8(void* args) {
  thread_yield();
  cout << "11615" << endl;
  thread_unlock(1);
  thread_broadcast(1, 0);
  thread_wait(2, 0);
  thread_yield();
  cout << "20992" << endl;
  thread_wait(0, 2);
  thread_broadcast(1, 2);
  thread_lock(2);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_wait(0, 1);
  thread_unlock(2);
  thread_yield();
  cout << "18839" << endl;
  thread_broadcast(1, 0);
  thread_unlock(2);
  thread_yield();
  thread_yield();
  thread_wait(1, 0);
  thread_yield();
}

void xyz9(void* args) {
  thread_broadcast(0, 0);
  cout << "1708840" << endl;
  thread_broadcast(1, 1);
  cout << "835492" << endl;
  thread_unlock(1);
  thread_wait(1, 0);
  cout << "1755512" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(0);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_broadcast(0, 0);
  thread_unlock(0);
  thread_unlock(1);
  thread_yield();
  thread_wait(1, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  cout << "2121960" << endl;
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(1, 1);
  thread_wait(0, 0);
  cout << "1543519" << endl;
  thread_yield();
  thread_yield();
  thread_signal(0, 1);
  thread_lock(0);
  thread_yield();
  thread_wait(1, 1);
  thread_signal(0, 1);
  thread_yield();
  thread_broadcast(1, 0);
  thread_unlock(0);
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_wait(0, 0);
  thread_yield();
  thread_unlock(0);
  thread_yield();
  thread_broadcast(0, 1);
  thread_broadcast(1, 0);
  thread_yield();
  thread_wait(0, 0);
  thread_yield();
  cout << "1078955" << endl;
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_lock(1);
  thread_signal(0, 1);
  thread_yield();
  cout << "809488" << endl;
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_signal(0, 0);
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
    thread_yield();
  }
  thread_yield();
  thread_wait(1, 1);
  thread_yield();
  thread_wait(0, 0);
  thread_yield();
  thread_broadcast(1, 0);
  thread_yield();
  cout << "214580" << endl;
  cout << "1952121" << endl;
  thread_signal(0, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_broadcast(0, 1);
}

void xyz10(void* args) {
  cout << "10676" << endl;
  thread_yield();
  thread_signal(4, 1);
  thread_wait(1, 5);
  thread_yield();
  thread_yield();
  thread_unlock(2);
  thread_yield();
  thread_wait(4, 2);
  thread_unlock(0);
  thread_unlock(2);
  thread_yield();
  thread_yield();
  thread_wait(4, 2);
  thread_wait(3, 5);
  thread_yield();
  cout << "3408" << endl;
  thread_yield();
  thread_yield();
  thread_wait(3, 1);
  cout << "121281" << endl;
  thread_lock(3);
  thread_yield();
  thread_broadcast(4, 4);
  thread_yield();
  for (int i = 0; i < 10; i ++) {
    cout << i << endl;
  }
  thread_yield();
  thread_broadcast(1, 5);
  thread_signal(3, 4);
  thread_yield();
  thread_yield();
  thread_broadcast(4, 4);
  cout << "185262" << endl;
  thread_yield();
  thread_wait(0, 4);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_yield();
  cout << "41048" << endl;
  thread_yield();
  thread_yield();
  thread_wait(1, 2);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(4, 2);
  thread_yield();
  thread_lock(0);
  thread_broadcast(1, 1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_broadcast(2, 1);
  thread_yield();
  thread_yield();
  thread_broadcast(0, 2);
  thread_yield();
}

void maker(void *args) {
  thread_create((thread_startfunc_t) xyz1, (void *) 100);
  thread_broadcast(0, 0);
  thread_wait(1, 1);
  thread_broadcast(0, 1);
  thread_yield();
  thread_unlock(0);
  thread_create((thread_startfunc_t) xyz2, (void *) 100);
  thread_unlock(1);
  thread_wait(0, 0);
  thread_create((thread_startfunc_t) xyz3, (void *) 100);
  thread_yield();
  thread_broadcast(0, 0);
  thread_create((thread_startfunc_t) xyz4, (void *) 100);
  thread_create((thread_startfunc_t) xyz5, (void *) 100);
  thread_create((thread_startfunc_t) xyz6, (void *) 100);
  thread_signal(1, 0);
  thread_lock(0);
  thread_create((thread_startfunc_t) xyz7, (void *) 100);
  thread_wait(1, 1);
  thread_create((thread_startfunc_t) xyz8, (void *) 100);
  thread_signal(0, 1);
  thread_create((thread_startfunc_t) xyz9, (void *) 100);
  thread_signal(0, 0);
  thread_create((thread_startfunc_t) xyz10, (void *) 100);
  thread_yield();
  thread_lock(0);
  thread_broadcast(0, 0);
  thread_signal(1, 0);
  thread_broadcast(1, 0);
  thread_unlock(0);
  thread_unlock(1);
  thread_yield();
  thread_lock(0);
  thread_broadcast(1, 0);
  thread_broadcast(1, 1);
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_yield();
  thread_signal(1, 0);
  thread_broadcast(1, 1);
  thread_broadcast(0, 0);
  thread_yield();
  thread_wait(1, 1);
  thread_yield();
  thread_unlock(1);
  thread_unlock(1);
  thread_unlock(1);
  thread_yield();
  thread_wait(1, 0);
  thread_lock(0);
  thread_wait(1, 1);
  thread_broadcast(0, 0);
  thread_lock(1);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_lock(0);
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_signal(1, 0);
  thread_yield();
  thread_unlock(1);
  thread_unlock(1);
  thread_yield();
  thread_unlock(0);
  thread_yield();
  thread_signal(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_yield();
  thread_wait(1, 1);
  thread_yield();
  thread_yield();
  thread_lock(1);
  thread_wait(1, 0);
  thread_yield();
  thread_yield();
  thread_yield();
  thread_signal(0, 1);
  thread_yield();
  thread_lock(1);
  thread_yield();
  thread_wait(0, 1);
  thread_yield();
  thread_yield();
  thread_unlock(1);
  thread_yield();
  thread_yield();
}

int main(int argc, char *argv[]) {
  thread_libinit((thread_startfunc_t)maker, &argc);
}
